apiVersion: 1
prune: true
datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmselect:8481/select/multitenant/prometheus
    isDefault: true
    editable: false
