// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: goplain/goplain.proto

package goplain

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	typepb "google.golang.org/protobuf/types/known/typepb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = typepb.Field_Kind(0)
)

// Validate checks the field values on GoIdent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoIdent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoIdent with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in GoIdentMultiError, or nil if none found.
func (m *GoIdent) ValidateAll() error {
	return m.validate(true)
}

func (m *GoIdent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for ImportPath

	if len(errors) > 0 {
		return GoIdentMultiError(errors)
	}

	return nil
}

// GoIdentMultiError is an error wrapping multiple validation errors returned
// by GoIdent.ValidateAll() if the designated constraints aren't met.
type GoIdentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoIdentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoIdentMultiError) AllErrors() []error { return m }

// GoIdentValidationError is the validation error returned by GoIdent.Validate
// if the designated constraints aren't met.
type GoIdentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoIdentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoIdentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoIdentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoIdentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoIdentValidationError) ErrorName() string { return "GoIdentValidationError" }

// Error satisfies the builtin error interface
func (e GoIdentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoIdent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoIdentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoIdentValidationError{}

// Validate checks the field values on OverrideSelector with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OverrideSelector) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OverrideSelector with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OverrideSelectorMultiError, or nil if none found.
func (m *OverrideSelector) ValidateAll() error {
	return m.validate(true)
}

func (m *OverrideSelector) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.TargetFullPath != nil {
		// no validation rules for TargetFullPath
	}

	if m.FieldKind != nil {
		// no validation rules for FieldKind
	}

	if m.FieldCardinality != nil {
		// no validation rules for FieldCardinality
	}

	if m.FieldTypeUrl != nil {
		// no validation rules for FieldTypeUrl
	}

	if len(errors) > 0 {
		return OverrideSelectorMultiError(errors)
	}

	return nil
}

// OverrideSelectorMultiError is an error wrapping multiple validation errors
// returned by OverrideSelector.ValidateAll() if the designated constraints
// aren't met.
type OverrideSelectorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OverrideSelectorMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OverrideSelectorMultiError) AllErrors() []error { return m }

// OverrideSelectorValidationError is the validation error returned by
// OverrideSelector.Validate if the designated constraints aren't met.
type OverrideSelectorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OverrideSelectorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OverrideSelectorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OverrideSelectorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OverrideSelectorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OverrideSelectorValidationError) ErrorName() string { return "OverrideSelectorValidationError" }

// Error satisfies the builtin error interface
func (e OverrideSelectorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOverrideSelector.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OverrideSelectorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OverrideSelectorValidationError{}

// Validate checks the field values on TypeOverride with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TypeOverride) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TypeOverride with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TypeOverrideMultiError, or
// nil if none found.
func (m *TypeOverride) ValidateAll() error {
	return m.validate(true)
}

func (m *TypeOverride) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSelector()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TypeOverrideValidationError{
					field:  "Selector",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TypeOverrideValidationError{
					field:  "Selector",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSelector()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TypeOverrideValidationError{
				field:  "Selector",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTargetGoType()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TypeOverrideValidationError{
					field:  "TargetGoType",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TypeOverrideValidationError{
					field:  "TargetGoType",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetGoType()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TypeOverrideValidationError{
				field:  "TargetGoType",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TypeOverrideMultiError(errors)
	}

	return nil
}

// TypeOverrideMultiError is an error wrapping multiple validation errors
// returned by TypeOverride.ValidateAll() if the designated constraints aren't met.
type TypeOverrideMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TypeOverrideMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TypeOverrideMultiError) AllErrors() []error { return m }

// TypeOverrideValidationError is the validation error returned by
// TypeOverride.Validate if the designated constraints aren't met.
type TypeOverrideValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TypeOverrideValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TypeOverrideValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TypeOverrideValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TypeOverrideValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TypeOverrideValidationError) ErrorName() string { return "TypeOverrideValidationError" }

// Error satisfies the builtin error interface
func (e TypeOverrideValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTypeOverride.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TypeOverrideValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TypeOverrideValidationError{}

// Validate checks the field values on MessageOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageOptions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageOptionsMultiError,
// or nil if none found.
func (m *MessageOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Generate

	// no validation rules for TypeAlias

	// no validation rules for TypeAliasField

	for idx, item := range m.GetVirtualFields() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MessageOptionsValidationError{
						field:  fmt.Sprintf("VirtualFields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MessageOptionsValidationError{
						field:  fmt.Sprintf("VirtualFields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MessageOptionsValidationError{
					field:  fmt.Sprintf("VirtualFields[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MessageOptionsMultiError(errors)
	}

	return nil
}

// MessageOptionsMultiError is an error wrapping multiple validation errors
// returned by MessageOptions.ValidateAll() if the designated constraints
// aren't met.
type MessageOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageOptionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageOptionsMultiError) AllErrors() []error { return m }

// MessageOptionsValidationError is the validation error returned by
// MessageOptions.Validate if the designated constraints aren't met.
type MessageOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageOptionsValidationError) ErrorName() string { return "MessageOptionsValidationError" }

// Error satisfies the builtin error interface
func (e MessageOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageOptionsValidationError{}

// Validate checks the field values on FileOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileOptionsMultiError, or
// nil if none found.
func (m *FileOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *FileOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetGoTypesOverrides() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FileOptionsValidationError{
						field:  fmt.Sprintf("GoTypesOverrides[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FileOptionsValidationError{
						field:  fmt.Sprintf("GoTypesOverrides[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FileOptionsValidationError{
					field:  fmt.Sprintf("GoTypesOverrides[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetVirtualTypes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FileOptionsValidationError{
						field:  fmt.Sprintf("VirtualTypes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FileOptionsValidationError{
						field:  fmt.Sprintf("VirtualTypes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FileOptionsValidationError{
					field:  fmt.Sprintf("VirtualTypes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FileOptionsMultiError(errors)
	}

	return nil
}

// FileOptionsMultiError is an error wrapping multiple validation errors
// returned by FileOptions.ValidateAll() if the designated constraints aren't met.
type FileOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileOptionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileOptionsMultiError) AllErrors() []error { return m }

// FileOptionsValidationError is the validation error returned by
// FileOptions.Validate if the designated constraints aren't met.
type FileOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileOptionsValidationError) ErrorName() string { return "FileOptionsValidationError" }

// Error satisfies the builtin error interface
func (e FileOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileOptionsValidationError{}

// Validate checks the field values on FieldOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FieldOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FieldOptions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FieldOptionsMultiError, or
// nil if none found.
func (m *FieldOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *FieldOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOverrideType()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FieldOptionsValidationError{
					field:  "OverrideType",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FieldOptionsValidationError{
					field:  "OverrideType",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOverrideType()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FieldOptionsValidationError{
				field:  "OverrideType",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Serialize

	// no validation rules for Embed

	// no validation rules for EmbedWithPrefix

	// no validation rules for EnumAsString

	// no validation rules for EnumAsInt

	// no validation rules for WriteDefault

	if len(errors) > 0 {
		return FieldOptionsMultiError(errors)
	}

	return nil
}

// FieldOptionsMultiError is an error wrapping multiple validation errors
// returned by FieldOptions.ValidateAll() if the designated constraints aren't met.
type FieldOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FieldOptionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FieldOptionsMultiError) AllErrors() []error { return m }

// FieldOptionsValidationError is the validation error returned by
// FieldOptions.Validate if the designated constraints aren't met.
type FieldOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FieldOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FieldOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FieldOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FieldOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FieldOptionsValidationError) ErrorName() string { return "FieldOptionsValidationError" }

// Error satisfies the builtin error interface
func (e FieldOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFieldOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FieldOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FieldOptionsValidationError{}

// Validate checks the field values on OneofOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OneofOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OneofOptions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OneofOptionsMultiError, or
// nil if none found.
func (m *OneofOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *OneofOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Embed

	// no validation rules for EmbedWithPrefix

	if len(errors) > 0 {
		return OneofOptionsMultiError(errors)
	}

	return nil
}

// OneofOptionsMultiError is an error wrapping multiple validation errors
// returned by OneofOptions.ValidateAll() if the designated constraints aren't met.
type OneofOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OneofOptionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OneofOptionsMultiError) AllErrors() []error { return m }

// OneofOptionsValidationError is the validation error returned by
// OneofOptions.Validate if the designated constraints aren't met.
type OneofOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OneofOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OneofOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OneofOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OneofOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OneofOptionsValidationError) ErrorName() string { return "OneofOptionsValidationError" }

// Error satisfies the builtin error interface
func (e OneofOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOneofOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OneofOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OneofOptionsValidationError{}
