// schemas-export writes every product schema for the web client:
//
//	<out>/<public id>.json   protoJSON of the schemapb Schema (fed to the TS engine/renderer)
//	<out>/<public id>.ts     TypeScript value types
//	<out>/index.ts           id → { schema, type } registry
//
// Usage: schemas-export -out ../web/src/schemas
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"

	"github.com/stroppy-io/stroppy-cloud/pipelines/schemas"
	"github.com/stroppy-io/stroppy-cloud/pipelines/schemas/ids"
	"github.com/stroppy-io/stroppy-cloud/pipelines/schemas/tsgen"
)

func main() {
	out := flag.String("out", "../web/src/schemas", "output directory")
	flag.Parse()
	if err := run(*out); err != nil {
		fmt.Fprintln(os.Stderr, "schemas-export:", err)
		os.Exit(1)
	}
}

func run(out string) error {
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	// wipe generated files so removed schemas disappear
	old, err := filepath.Glob(filepath.Join(out, "*"))
	if err != nil {
		return err
	}
	for _, p := range old {
		if strings.HasSuffix(p, ".json") || strings.HasSuffix(p, ".ts") {
			_ = os.Remove(p)
		}
	}
	type entry struct{ id, file, typ string }
	var entries []entry
	for _, s := range schemas.All() {
		id := ids.Public(s.GetId())
		file := strings.ReplaceAll(id, "@", "_v")
		js, err := protojson.MarshalOptions{Multiline: true, Indent: "  "}.Marshal(s)
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(out, file+".json"), append(js, '\n'), 0o644); err != nil { //nolint:gosec // generated source, world-readable by design
			return err
		}
		types := strings.TrimRight(tsgen.Generate(s), "\n") + "\n"
		if err := os.WriteFile(filepath.Join(out, file+".ts"), []byte(types), 0o644); err != nil { //nolint:gosec // generated source
			return err
		}
		entries = append(entries, entry{id: id, file: file, typ: tsgen.TypeName(s.GetId())})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].id < entries[j].id })
	var sb strings.Builder
	sb.WriteString("// GENERATED by pipelines/cmd/schemas-export — do not edit.\n")
	sb.WriteString("// Registry of every product schemapb schema: protoJSON for the engine + value types.\n\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "import %sSchema from './%s.json';\n", lower(e.typ), e.file)
		fmt.Fprintf(&sb, "import type { %s } from './%s';\n", e.typ, e.file)
	}
	sb.WriteString("\nexport const schemaIds = [\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "  %q,\n", e.id)
	}
	sb.WriteString("] as const;\nexport type SchemaId = (typeof schemaIds)[number];\n\n")
	sb.WriteString("/** Value type of a schema id. */\nexport type SchemaValue<Id extends SchemaId> =\n")
	for i, e := range entries {
		sep := " :"
		if i == len(entries)-1 {
			sep = " : never;"
		}
		fmt.Fprintf(&sb, "  Id extends %q ? %s%s\n", e.id, e.typ, sep)
	}
	sb.WriteString("\n/** protoJSON schemas keyed by id. */\nexport const schemas: Record<SchemaId, unknown> = {\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "  %q: %sSchema,\n", e.id, lower(e.typ))
	}
	sb.WriteString("};\n\nexport type {\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "  %s,\n", e.typ)
	}
	sb.WriteString("};\n")
	if err := os.WriteFile(filepath.Join(out, "index.ts"), []byte(sb.String()), 0o644); err != nil { //nolint:gosec // generated source
		return err
	}
	fmt.Printf("exported %d schemas to %s\n", len(entries), out)
	return nil
}

func lower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
