// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=ts"
// @generated from file api/v1/auth.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse, RefreshTokenRequest, RefreshTokenResponse } from "./auth_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1.AuthAPI
 */
export const AuthAPI = {
  typeName: "api.v1.AuthAPI",
  methods: {
    /**
     * @generated from rpc api.v1.AuthAPI.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.v1.AuthAPI.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: RefreshTokenRequest,
      O: RefreshTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

