// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: database/picodata.proto

package database

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Picodata with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Picodata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PicodataMultiError, or nil
// if none found.
func (m *Picodata) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PicodataMultiError(errors)
	}

	return nil
}

// PicodataMultiError is an error wrapping multiple validation errors returned
// by Picodata.ValidateAll() if the designated constraints aren't met.
type PicodataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PicodataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PicodataMultiError) AllErrors() []error { return m }

// PicodataValidationError is the validation error returned by
// Picodata.Validate if the designated constraints aren't met.
type PicodataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PicodataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PicodataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PicodataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PicodataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PicodataValidationError) ErrorName() string { return "PicodataValidationError" }

// Error satisfies the builtin error interface
func (e PicodataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PicodataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PicodataValidationError{}

// Validate checks the field values on Picodata_Sidecar with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Sidecar) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Sidecar with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_SidecarMultiError, or nil if none found.
func (m *Picodata_Sidecar) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Sidecar) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofSidecarPresent := false
	switch v := m.Sidecar.(type) {
	case *Picodata_Sidecar_NodeExporter:
		if v == nil {
			err := Picodata_SidecarValidationError{
				field:  "Sidecar",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofSidecarPresent = true

		if all {
			switch v := interface{}(m.GetNodeExporter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_SidecarValidationError{
						field:  "NodeExporter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_SidecarValidationError{
						field:  "NodeExporter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetNodeExporter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_SidecarValidationError{
					field:  "NodeExporter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Picodata_Sidecar_HttpMetrics_:
		if v == nil {
			err := Picodata_SidecarValidationError{
				field:  "Sidecar",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofSidecarPresent = true

		if all {
			switch v := interface{}(m.GetHttpMetrics()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_SidecarValidationError{
						field:  "HttpMetrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_SidecarValidationError{
						field:  "HttpMetrics",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetHttpMetrics()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_SidecarValidationError{
					field:  "HttpMetrics",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Picodata_Sidecar_Backup_:
		if v == nil {
			err := Picodata_SidecarValidationError{
				field:  "Sidecar",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofSidecarPresent = true

		if all {
			switch v := interface{}(m.GetBackup()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_SidecarValidationError{
						field:  "Backup",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_SidecarValidationError{
						field:  "Backup",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBackup()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_SidecarValidationError{
					field:  "Backup",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofSidecarPresent {
		err := Picodata_SidecarValidationError{
			field:  "Sidecar",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return Picodata_SidecarMultiError(errors)
	}

	return nil
}

// Picodata_SidecarMultiError is an error wrapping multiple validation errors
// returned by Picodata_Sidecar.ValidateAll() if the designated constraints
// aren't met.
type Picodata_SidecarMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_SidecarMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_SidecarMultiError) AllErrors() []error { return m }

// Picodata_SidecarValidationError is the validation error returned by
// Picodata_Sidecar.Validate if the designated constraints aren't met.
type Picodata_SidecarValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_SidecarValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_SidecarValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_SidecarValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_SidecarValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_SidecarValidationError) ErrorName() string { return "Picodata_SidecarValidationError" }

// Error satisfies the builtin error interface
func (e Picodata_SidecarValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Sidecar.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_SidecarValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_SidecarValidationError{}

// Validate checks the field values on Picodata_Placement with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Placement) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Placement with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_PlacementMultiError, or nil if none found.
func (m *Picodata_Placement) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Placement) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofModePresent := false
	switch v := m.Mode.(type) {
	case *Picodata_Placement_Colocate_:
		if v == nil {
			err := Picodata_PlacementValidationError{
				field:  "Mode",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofModePresent = true

		if all {
			switch v := interface{}(m.GetColocate()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_PlacementValidationError{
						field:  "Colocate",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_PlacementValidationError{
						field:  "Colocate",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetColocate()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_PlacementValidationError{
					field:  "Colocate",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Picodata_Placement_Dedicated_:
		if v == nil {
			err := Picodata_PlacementValidationError{
				field:  "Mode",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofModePresent = true

		if all {
			switch v := interface{}(m.GetDedicated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_PlacementValidationError{
						field:  "Dedicated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_PlacementValidationError{
						field:  "Dedicated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDedicated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_PlacementValidationError{
					field:  "Dedicated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofModePresent {
		err := Picodata_PlacementValidationError{
			field:  "Mode",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return Picodata_PlacementMultiError(errors)
	}

	return nil
}

// Picodata_PlacementMultiError is an error wrapping multiple validation errors
// returned by Picodata_Placement.ValidateAll() if the designated constraints
// aren't met.
type Picodata_PlacementMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_PlacementMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_PlacementMultiError) AllErrors() []error { return m }

// Picodata_PlacementValidationError is the validation error returned by
// Picodata_Placement.Validate if the designated constraints aren't met.
type Picodata_PlacementValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_PlacementValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_PlacementValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_PlacementValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_PlacementValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_PlacementValidationError) ErrorName() string {
	return "Picodata_PlacementValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_PlacementValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Placement.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_PlacementValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_PlacementValidationError{}

// Validate checks the field values on Picodata_Settings with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Settings) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Settings with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_SettingsMultiError, or nil if none found.
func (m *Picodata_Settings) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Settings) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetVersion()) < 1 {
		err := Picodata_SettingsValidationError{
			field:  "Version",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Picodata_Settings_StorageEngine_name[int32(m.GetStorageEngine())]; !ok {
		err := Picodata_SettingsValidationError{
			field:  "StorageEngine",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PicodataConf

	if len(errors) > 0 {
		return Picodata_SettingsMultiError(errors)
	}

	return nil
}

// Picodata_SettingsMultiError is an error wrapping multiple validation errors
// returned by Picodata_Settings.ValidateAll() if the designated constraints
// aren't met.
type Picodata_SettingsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_SettingsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_SettingsMultiError) AllErrors() []error { return m }

// Picodata_SettingsValidationError is the validation error returned by
// Picodata_Settings.Validate if the designated constraints aren't met.
type Picodata_SettingsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_SettingsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_SettingsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_SettingsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_SettingsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_SettingsValidationError) ErrorName() string {
	return "Picodata_SettingsValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_SettingsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Settings.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_SettingsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_SettingsValidationError{}

// Validate checks the field values on Picodata_Addons with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Addons) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Addons with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_AddonsMultiError, or nil if none found.
func (m *Picodata_Addons) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Addons) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBackup()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_AddonsValidationError{
					field:  "Backup",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_AddonsValidationError{
					field:  "Backup",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBackup()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_AddonsValidationError{
				field:  "Backup",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Picodata_AddonsMultiError(errors)
	}

	return nil
}

// Picodata_AddonsMultiError is an error wrapping multiple validation errors
// returned by Picodata_Addons.ValidateAll() if the designated constraints
// aren't met.
type Picodata_AddonsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_AddonsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_AddonsMultiError) AllErrors() []error { return m }

// Picodata_AddonsValidationError is the validation error returned by
// Picodata_Addons.Validate if the designated constraints aren't met.
type Picodata_AddonsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_AddonsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_AddonsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_AddonsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_AddonsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_AddonsValidationError) ErrorName() string { return "Picodata_AddonsValidationError" }

// Error satisfies the builtin error interface
func (e Picodata_AddonsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Addons.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_AddonsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_AddonsValidationError{}

// Validate checks the field values on Picodata_Instance with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Instance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Instance with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_InstanceMultiError, or nil if none found.
func (m *Picodata_Instance) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Instance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTemplate() == nil {
		err := Picodata_InstanceValidationError{
			field:  "Template",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_InstanceValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_InstanceValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_InstanceValidationError{
				field:  "Template",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetSidecars() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_InstanceValidationError{
						field:  fmt.Sprintf("Sidecars[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_InstanceValidationError{
						field:  fmt.Sprintf("Sidecars[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_InstanceValidationError{
					field:  fmt.Sprintf("Sidecars[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return Picodata_InstanceMultiError(errors)
	}

	return nil
}

// Picodata_InstanceMultiError is an error wrapping multiple validation errors
// returned by Picodata_Instance.ValidateAll() if the designated constraints
// aren't met.
type Picodata_InstanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_InstanceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_InstanceMultiError) AllErrors() []error { return m }

// Picodata_InstanceValidationError is the validation error returned by
// Picodata_Instance.Validate if the designated constraints aren't met.
type Picodata_InstanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_InstanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_InstanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_InstanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_InstanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_InstanceValidationError) ErrorName() string {
	return "Picodata_InstanceValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_InstanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Instance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_InstanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_InstanceValidationError{}

// Validate checks the field values on Picodata_Cluster with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Cluster) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Cluster with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_ClusterMultiError, or nil if none found.
func (m *Picodata_Cluster) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Cluster) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTemplate() == nil {
		err := Picodata_ClusterValidationError{
			field:  "Template",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTemplate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_ClusterValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_ClusterValidationError{
					field:  "Template",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTemplate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_ClusterValidationError{
				field:  "Template",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetNodes()) < 1 {
		err := Picodata_ClusterValidationError{
			field:  "Nodes",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetNodes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_ClusterValidationError{
						field:  fmt.Sprintf("Nodes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_ClusterValidationError{
						field:  fmt.Sprintf("Nodes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_ClusterValidationError{
					field:  fmt.Sprintf("Nodes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return Picodata_ClusterMultiError(errors)
	}

	return nil
}

// Picodata_ClusterMultiError is an error wrapping multiple validation errors
// returned by Picodata_Cluster.ValidateAll() if the designated constraints
// aren't met.
type Picodata_ClusterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_ClusterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_ClusterMultiError) AllErrors() []error { return m }

// Picodata_ClusterValidationError is the validation error returned by
// Picodata_Cluster.Validate if the designated constraints aren't met.
type Picodata_ClusterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_ClusterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_ClusterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_ClusterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_ClusterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_ClusterValidationError) ErrorName() string { return "Picodata_ClusterValidationError" }

// Error satisfies the builtin error interface
func (e Picodata_ClusterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Cluster.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_ClusterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_ClusterValidationError{}

// Validate checks the field values on Picodata_Sidecar_HttpMetrics with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Sidecar_HttpMetrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Sidecar_HttpMetrics with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_Sidecar_HttpMetricsMultiError, or nil if none found.
func (m *Picodata_Sidecar_HttpMetrics) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Sidecar_HttpMetrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enabled

	// no validation rules for Port

	if len(errors) > 0 {
		return Picodata_Sidecar_HttpMetricsMultiError(errors)
	}

	return nil
}

// Picodata_Sidecar_HttpMetricsMultiError is an error wrapping multiple
// validation errors returned by Picodata_Sidecar_HttpMetrics.ValidateAll() if
// the designated constraints aren't met.
type Picodata_Sidecar_HttpMetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Sidecar_HttpMetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Sidecar_HttpMetricsMultiError) AllErrors() []error { return m }

// Picodata_Sidecar_HttpMetricsValidationError is the validation error returned
// by Picodata_Sidecar_HttpMetrics.Validate if the designated constraints
// aren't met.
type Picodata_Sidecar_HttpMetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Sidecar_HttpMetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Sidecar_HttpMetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Sidecar_HttpMetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Sidecar_HttpMetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Sidecar_HttpMetricsValidationError) ErrorName() string {
	return "Picodata_Sidecar_HttpMetricsValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Sidecar_HttpMetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Sidecar_HttpMetrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Sidecar_HttpMetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Sidecar_HttpMetricsValidationError{}

// Validate checks the field values on Picodata_Sidecar_Backup with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Sidecar_Backup) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Sidecar_Backup with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_Sidecar_BackupMultiError, or nil if none found.
func (m *Picodata_Sidecar_Backup) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Sidecar_Backup) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSchedule()) < 1 {
		err := Picodata_Sidecar_BackupValidationError{
			field:  "Schedule",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Retention

	if _, ok := Picodata_Sidecar_Backup_Tool_name[int32(m.GetTool())]; !ok {
		err := Picodata_Sidecar_BackupValidationError{
			field:  "Tool",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	oneofStoragePresent := false
	switch v := m.Storage.(type) {
	case *Picodata_Sidecar_Backup_S3:
		if v == nil {
			err := Picodata_Sidecar_BackupValidationError{
				field:  "Storage",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofStoragePresent = true

		if all {
			switch v := interface{}(m.GetS3()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_Sidecar_BackupValidationError{
						field:  "S3",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_Sidecar_BackupValidationError{
						field:  "S3",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetS3()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_Sidecar_BackupValidationError{
					field:  "S3",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Picodata_Sidecar_Backup_Local:
		if v == nil {
			err := Picodata_Sidecar_BackupValidationError{
				field:  "Storage",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofStoragePresent = true

		if all {
			switch v := interface{}(m.GetLocal()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_Sidecar_BackupValidationError{
						field:  "Local",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_Sidecar_BackupValidationError{
						field:  "Local",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLocal()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_Sidecar_BackupValidationError{
					field:  "Local",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofStoragePresent {
		err := Picodata_Sidecar_BackupValidationError{
			field:  "Storage",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return Picodata_Sidecar_BackupMultiError(errors)
	}

	return nil
}

// Picodata_Sidecar_BackupMultiError is an error wrapping multiple validation
// errors returned by Picodata_Sidecar_Backup.ValidateAll() if the designated
// constraints aren't met.
type Picodata_Sidecar_BackupMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Sidecar_BackupMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Sidecar_BackupMultiError) AllErrors() []error { return m }

// Picodata_Sidecar_BackupValidationError is the validation error returned by
// Picodata_Sidecar_Backup.Validate if the designated constraints aren't met.
type Picodata_Sidecar_BackupValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Sidecar_BackupValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Sidecar_BackupValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Sidecar_BackupValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Sidecar_BackupValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Sidecar_BackupValidationError) ErrorName() string {
	return "Picodata_Sidecar_BackupValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Sidecar_BackupValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Sidecar_Backup.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Sidecar_BackupValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Sidecar_BackupValidationError{}

// Validate checks the field values on Picodata_Sidecar_Backup_S3Storage with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *Picodata_Sidecar_Backup_S3Storage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Sidecar_Backup_S3Storage
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// Picodata_Sidecar_Backup_S3StorageMultiError, or nil if none found.
func (m *Picodata_Sidecar_Backup_S3Storage) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Sidecar_Backup_S3Storage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBucket()) < 1 {
		err := Picodata_Sidecar_Backup_S3StorageValidationError{
			field:  "Bucket",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRegion()) < 1 {
		err := Picodata_Sidecar_Backup_S3StorageValidationError{
			field:  "Region",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetEndpoint()) < 1 {
		err := Picodata_Sidecar_Backup_S3StorageValidationError{
			field:  "Endpoint",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAccessKeyId()) < 1 {
		err := Picodata_Sidecar_Backup_S3StorageValidationError{
			field:  "AccessKeyId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSecretAccessKey()) < 1 {
		err := Picodata_Sidecar_Backup_S3StorageValidationError{
			field:  "SecretAccessKey",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return Picodata_Sidecar_Backup_S3StorageMultiError(errors)
	}

	return nil
}

// Picodata_Sidecar_Backup_S3StorageMultiError is an error wrapping multiple
// validation errors returned by
// Picodata_Sidecar_Backup_S3Storage.ValidateAll() if the designated
// constraints aren't met.
type Picodata_Sidecar_Backup_S3StorageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Sidecar_Backup_S3StorageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Sidecar_Backup_S3StorageMultiError) AllErrors() []error { return m }

// Picodata_Sidecar_Backup_S3StorageValidationError is the validation error
// returned by Picodata_Sidecar_Backup_S3Storage.Validate if the designated
// constraints aren't met.
type Picodata_Sidecar_Backup_S3StorageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Sidecar_Backup_S3StorageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Sidecar_Backup_S3StorageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Sidecar_Backup_S3StorageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Sidecar_Backup_S3StorageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Sidecar_Backup_S3StorageValidationError) ErrorName() string {
	return "Picodata_Sidecar_Backup_S3StorageValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Sidecar_Backup_S3StorageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Sidecar_Backup_S3Storage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Sidecar_Backup_S3StorageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Sidecar_Backup_S3StorageValidationError{}

// Validate checks the field values on Picodata_Sidecar_Backup_LocalStorage
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *Picodata_Sidecar_Backup_LocalStorage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Sidecar_Backup_LocalStorage
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// Picodata_Sidecar_Backup_LocalStorageMultiError, or nil if none found.
func (m *Picodata_Sidecar_Backup_LocalStorage) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Sidecar_Backup_LocalStorage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetPath()) < 1 {
		err := Picodata_Sidecar_Backup_LocalStorageValidationError{
			field:  "Path",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return Picodata_Sidecar_Backup_LocalStorageMultiError(errors)
	}

	return nil
}

// Picodata_Sidecar_Backup_LocalStorageMultiError is an error wrapping multiple
// validation errors returned by
// Picodata_Sidecar_Backup_LocalStorage.ValidateAll() if the designated
// constraints aren't met.
type Picodata_Sidecar_Backup_LocalStorageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Sidecar_Backup_LocalStorageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Sidecar_Backup_LocalStorageMultiError) AllErrors() []error { return m }

// Picodata_Sidecar_Backup_LocalStorageValidationError is the validation error
// returned by Picodata_Sidecar_Backup_LocalStorage.Validate if the designated
// constraints aren't met.
type Picodata_Sidecar_Backup_LocalStorageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Sidecar_Backup_LocalStorageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Sidecar_Backup_LocalStorageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Sidecar_Backup_LocalStorageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Sidecar_Backup_LocalStorageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Sidecar_Backup_LocalStorageValidationError) ErrorName() string {
	return "Picodata_Sidecar_Backup_LocalStorageValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Sidecar_Backup_LocalStorageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Sidecar_Backup_LocalStorage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Sidecar_Backup_LocalStorageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Sidecar_Backup_LocalStorageValidationError{}

// Validate checks the field values on Picodata_Placement_Colocate with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Placement_Colocate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Placement_Colocate with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_Placement_ColocateMultiError, or nil if none found.
func (m *Picodata_Placement_Colocate) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Placement_Colocate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := Picodata_Placement_Scope_name[int32(m.GetScope())]; !ok {
		err := Picodata_Placement_ColocateValidationError{
			field:  "Scope",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.NodeIndex != nil {
		// no validation rules for NodeIndex
	}

	if len(errors) > 0 {
		return Picodata_Placement_ColocateMultiError(errors)
	}

	return nil
}

// Picodata_Placement_ColocateMultiError is an error wrapping multiple
// validation errors returned by Picodata_Placement_Colocate.ValidateAll() if
// the designated constraints aren't met.
type Picodata_Placement_ColocateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Placement_ColocateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Placement_ColocateMultiError) AllErrors() []error { return m }

// Picodata_Placement_ColocateValidationError is the validation error returned
// by Picodata_Placement_Colocate.Validate if the designated constraints
// aren't met.
type Picodata_Placement_ColocateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Placement_ColocateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Placement_ColocateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Placement_ColocateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Placement_ColocateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Placement_ColocateValidationError) ErrorName() string {
	return "Picodata_Placement_ColocateValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Placement_ColocateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Placement_Colocate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Placement_ColocateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Placement_ColocateValidationError{}

// Validate checks the field values on Picodata_Placement_Dedicated with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Placement_Dedicated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Placement_Dedicated with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_Placement_DedicatedMultiError, or nil if none found.
func (m *Picodata_Placement_Dedicated) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Placement_Dedicated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetInstancesCount(); val < 1 || val > 5 {
		err := Picodata_Placement_DedicatedValidationError{
			field:  "InstancesCount",
			reason: "value must be inside range [1, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetHardware() == nil {
		err := Picodata_Placement_DedicatedValidationError{
			field:  "Hardware",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHardware()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Placement_DedicatedValidationError{
					field:  "Hardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Placement_DedicatedValidationError{
					field:  "Hardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHardware()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Placement_DedicatedValidationError{
				field:  "Hardware",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Picodata_Placement_DedicatedMultiError(errors)
	}

	return nil
}

// Picodata_Placement_DedicatedMultiError is an error wrapping multiple
// validation errors returned by Picodata_Placement_Dedicated.ValidateAll() if
// the designated constraints aren't met.
type Picodata_Placement_DedicatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Placement_DedicatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Placement_DedicatedMultiError) AllErrors() []error { return m }

// Picodata_Placement_DedicatedValidationError is the validation error returned
// by Picodata_Placement_Dedicated.Validate if the designated constraints
// aren't met.
type Picodata_Placement_DedicatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Placement_DedicatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Placement_DedicatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Placement_DedicatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Placement_DedicatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Placement_DedicatedValidationError) ErrorName() string {
	return "Picodata_Placement_DedicatedValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Placement_DedicatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Placement_Dedicated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Placement_DedicatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Placement_DedicatedValidationError{}

// Validate checks the field values on Picodata_Addons_Backup with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Addons_Backup) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Addons_Backup with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_Addons_BackupMultiError, or nil if none found.
func (m *Picodata_Addons_Backup) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Addons_Backup) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enabled

	if _, ok := Picodata_Placement_Scope_name[int32(m.GetScope())]; !ok {
		err := Picodata_Addons_BackupValidationError{
			field:  "Scope",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Addons_BackupValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Addons_BackupValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Addons_BackupValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Picodata_Addons_BackupMultiError(errors)
	}

	return nil
}

// Picodata_Addons_BackupMultiError is an error wrapping multiple validation
// errors returned by Picodata_Addons_Backup.ValidateAll() if the designated
// constraints aren't met.
type Picodata_Addons_BackupMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Addons_BackupMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Addons_BackupMultiError) AllErrors() []error { return m }

// Picodata_Addons_BackupValidationError is the validation error returned by
// Picodata_Addons_Backup.Validate if the designated constraints aren't met.
type Picodata_Addons_BackupValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Addons_BackupValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Addons_BackupValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Addons_BackupValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Addons_BackupValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Addons_BackupValidationError) ErrorName() string {
	return "Picodata_Addons_BackupValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Addons_BackupValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Addons_Backup.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Addons_BackupValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Addons_BackupValidationError{}

// Validate checks the field values on Picodata_Instance_Template with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Instance_Template) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Instance_Template with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_Instance_TemplateMultiError, or nil if none found.
func (m *Picodata_Instance_Template) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Instance_Template) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSettings() == nil {
		err := Picodata_Instance_TemplateValidationError{
			field:  "Settings",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSettings()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Instance_TemplateValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Instance_TemplateValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Instance_TemplateValidationError{
				field:  "Settings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetHardware() == nil {
		err := Picodata_Instance_TemplateValidationError{
			field:  "Hardware",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHardware()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Instance_TemplateValidationError{
					field:  "Hardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Instance_TemplateValidationError{
					field:  "Hardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHardware()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Instance_TemplateValidationError{
				field:  "Hardware",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetSidecars() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_Instance_TemplateValidationError{
						field:  fmt.Sprintf("Sidecars[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_Instance_TemplateValidationError{
						field:  fmt.Sprintf("Sidecars[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_Instance_TemplateValidationError{
					field:  fmt.Sprintf("Sidecars[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return Picodata_Instance_TemplateMultiError(errors)
	}

	return nil
}

// Picodata_Instance_TemplateMultiError is an error wrapping multiple
// validation errors returned by Picodata_Instance_Template.ValidateAll() if
// the designated constraints aren't met.
type Picodata_Instance_TemplateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Instance_TemplateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Instance_TemplateMultiError) AllErrors() []error { return m }

// Picodata_Instance_TemplateValidationError is the validation error returned
// by Picodata_Instance_Template.Validate if the designated constraints aren't met.
type Picodata_Instance_TemplateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Instance_TemplateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Instance_TemplateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Instance_TemplateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Instance_TemplateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Instance_TemplateValidationError) ErrorName() string {
	return "Picodata_Instance_TemplateValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Instance_TemplateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Instance_Template.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Instance_TemplateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Instance_TemplateValidationError{}

// Validate checks the field values on Picodata_Cluster_Template with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Picodata_Cluster_Template) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Cluster_Template with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Picodata_Cluster_TemplateMultiError, or nil if none found.
func (m *Picodata_Cluster_Template) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Cluster_Template) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetTopology() == nil {
		err := Picodata_Cluster_TemplateValidationError{
			field:  "Topology",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTopology()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Cluster_TemplateValidationError{
					field:  "Topology",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Cluster_TemplateValidationError{
					field:  "Topology",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTopology()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Cluster_TemplateValidationError{
				field:  "Topology",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAddons()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Cluster_TemplateValidationError{
					field:  "Addons",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Cluster_TemplateValidationError{
					field:  "Addons",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAddons()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Cluster_TemplateValidationError{
				field:  "Addons",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetNodeOverrides() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Picodata_Cluster_TemplateValidationError{
						field:  fmt.Sprintf("NodeOverrides[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Picodata_Cluster_TemplateValidationError{
						field:  fmt.Sprintf("NodeOverrides[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Picodata_Cluster_TemplateValidationError{
					field:  fmt.Sprintf("NodeOverrides[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return Picodata_Cluster_TemplateMultiError(errors)
	}

	return nil
}

// Picodata_Cluster_TemplateMultiError is an error wrapping multiple validation
// errors returned by Picodata_Cluster_Template.ValidateAll() if the
// designated constraints aren't met.
type Picodata_Cluster_TemplateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Cluster_TemplateMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Cluster_TemplateMultiError) AllErrors() []error { return m }

// Picodata_Cluster_TemplateValidationError is the validation error returned by
// Picodata_Cluster_Template.Validate if the designated constraints aren't met.
type Picodata_Cluster_TemplateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Cluster_TemplateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Cluster_TemplateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Cluster_TemplateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Cluster_TemplateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Cluster_TemplateValidationError) ErrorName() string {
	return "Picodata_Cluster_TemplateValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Cluster_TemplateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Cluster_Template.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Cluster_TemplateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Cluster_TemplateValidationError{}

// Validate checks the field values on Picodata_Cluster_Template_Topology with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *Picodata_Cluster_Template_Topology) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Picodata_Cluster_Template_Topology
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// Picodata_Cluster_Template_TopologyMultiError, or nil if none found.
func (m *Picodata_Cluster_Template_Topology) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Cluster_Template_Topology) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSettings() == nil {
		err := Picodata_Cluster_Template_TopologyValidationError{
			field:  "Settings",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetSettings()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_TopologyValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_TopologyValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Cluster_Template_TopologyValidationError{
				field:  "Settings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetNodeHardware() == nil {
		err := Picodata_Cluster_Template_TopologyValidationError{
			field:  "NodeHardware",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetNodeHardware()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_TopologyValidationError{
					field:  "NodeHardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_TopologyValidationError{
					field:  "NodeHardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNodeHardware()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Cluster_Template_TopologyValidationError{
				field:  "NodeHardware",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetNodesCount() < 1 {
		err := Picodata_Cluster_Template_TopologyValidationError{
			field:  "NodesCount",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Monitor

	if len(errors) > 0 {
		return Picodata_Cluster_Template_TopologyMultiError(errors)
	}

	return nil
}

// Picodata_Cluster_Template_TopologyMultiError is an error wrapping multiple
// validation errors returned by
// Picodata_Cluster_Template_Topology.ValidateAll() if the designated
// constraints aren't met.
type Picodata_Cluster_Template_TopologyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Cluster_Template_TopologyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Cluster_Template_TopologyMultiError) AllErrors() []error { return m }

// Picodata_Cluster_Template_TopologyValidationError is the validation error
// returned by Picodata_Cluster_Template_Topology.Validate if the designated
// constraints aren't met.
type Picodata_Cluster_Template_TopologyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Cluster_Template_TopologyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Cluster_Template_TopologyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Cluster_Template_TopologyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Cluster_Template_TopologyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Cluster_Template_TopologyValidationError) ErrorName() string {
	return "Picodata_Cluster_Template_TopologyValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Cluster_Template_TopologyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Cluster_Template_Topology.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Cluster_Template_TopologyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Cluster_Template_TopologyValidationError{}

// Validate checks the field values on Picodata_Cluster_Template_NodeOverride
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *Picodata_Cluster_Template_NodeOverride) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// Picodata_Cluster_Template_NodeOverride with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// Picodata_Cluster_Template_NodeOverrideMultiError, or nil if none found.
func (m *Picodata_Cluster_Template_NodeOverride) ValidateAll() error {
	return m.validate(true)
}

func (m *Picodata_Cluster_Template_NodeOverride) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NodeIndex

	if all {
		switch v := interface{}(m.GetSettings()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_NodeOverrideValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_NodeOverrideValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Cluster_Template_NodeOverrideValidationError{
				field:  "Settings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetHardware()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_NodeOverrideValidationError{
					field:  "Hardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, Picodata_Cluster_Template_NodeOverrideValidationError{
					field:  "Hardware",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHardware()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return Picodata_Cluster_Template_NodeOverrideValidationError{
				field:  "Hardware",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return Picodata_Cluster_Template_NodeOverrideMultiError(errors)
	}

	return nil
}

// Picodata_Cluster_Template_NodeOverrideMultiError is an error wrapping
// multiple validation errors returned by
// Picodata_Cluster_Template_NodeOverride.ValidateAll() if the designated
// constraints aren't met.
type Picodata_Cluster_Template_NodeOverrideMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Picodata_Cluster_Template_NodeOverrideMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Picodata_Cluster_Template_NodeOverrideMultiError) AllErrors() []error { return m }

// Picodata_Cluster_Template_NodeOverrideValidationError is the validation
// error returned by Picodata_Cluster_Template_NodeOverride.Validate if the
// designated constraints aren't met.
type Picodata_Cluster_Template_NodeOverrideValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Picodata_Cluster_Template_NodeOverrideValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Picodata_Cluster_Template_NodeOverrideValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Picodata_Cluster_Template_NodeOverrideValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Picodata_Cluster_Template_NodeOverrideValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Picodata_Cluster_Template_NodeOverrideValidationError) ErrorName() string {
	return "Picodata_Cluster_Template_NodeOverrideValidationError"
}

// Error satisfies the builtin error interface
func (e Picodata_Cluster_Template_NodeOverrideValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPicodata_Cluster_Template_NodeOverride.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Picodata_Cluster_Template_NodeOverrideValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Picodata_Cluster_Template_NodeOverrideValidationError{}
