// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=ts,json_types=true,valid_types=legacy_required+protovalidate_required"
// @generated from file stroppy/test.proto (package stroppy, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Database_Template, Database_TemplateJson } from "../database/database_pb.ts";
import { file_database_database } from "../database/database_pb.ts";
import type { Hardware, HardwareJson, Target, TargetJson } from "../deployment/deployment_pb.ts";
import { file_deployment_deployment } from "../deployment/deployment_pb.ts";
import type { Duration, DurationJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Settings, SettingsJson } from "../settings/settings_pb.ts";
import { file_settings_settings } from "../settings/settings_pb.ts";
import { file_validate_validate } from "../validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file stroppy/test.proto.
 */
export const file_stroppy_test: GenFile = /*@__PURE__*/
  fileDesc("ChJzdHJvcHB5L3Rlc3QucHJvdG8SB3N0cm9wcHki5gMKClN0cm9wcHlDbGkSGAoHdmVyc2lvbhgBIAEoCUIH+kIEcgIQARIxCgtiaW5hcnlfcGF0aBgCIAEoCUIc+kIZchcyFV4vKD86W14vAF0rLykqW14vAF0qJBItCgd3b3JrZGlyGAMgASgJQhz6QhlyFzIVXi8oPzpbXi8AXSsvKSpbXi8AXSokEjgKCHdvcmtsb2FkGAQgASgOMhwuc3Ryb3BweS5TdHJvcHB5Q2xpLldvcmtsb2FkQgj6QgWCAQIQARIZCgxzY2FsZV9mYWN0b3IYBSABKA1IAIgBARJCCghkdXJhdGlvbhgGIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkIQ+kINqgEKMgIIASIECICjBUgBiAEBEjgKC3N0cm9wcHlfZW52GAcgAygLMiMuc3Ryb3BweS5TdHJvcHB5Q2xpLlN0cm9wcHlFbnZFbnRyeRoxCg9TdHJvcHB5RW52RW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASI4CghXb3JrbG9hZBIYChRXT1JLTE9BRF9VTlNQRUNJRklFRBAAEggKBFRQQ0MQARIICgRUUENCEAJCDwoNX3NjYWxlX2ZhY3RvckILCglfZHVyYXRpb24inAIKBFRlc3QSDAoEbmFtZRgCIAEoCRIYCgtkZXNjcmlwdGlvbhgDIAEoCUgBiAEBEjIKC3N0cm9wcHlfY2xpGAQgASgLMhMuc3Ryb3BweS5TdHJvcHB5Q2xpQgj6QgWKAQIQARI4ChBzdHJvcHB5X2hhcmR3YXJlGAcgASgLMhQuZGVwbG95bWVudC5IYXJkd2FyZUII+kIFigECEAESOAoRZGF0YWJhc2VfdGVtcGxhdGUYZSABKAsyGy5kYXRhYmFzZS5EYXRhYmFzZS5UZW1wbGF0ZUgAEiQKEWNvbm5lY3Rpb25fc3RyaW5nGGYgASgJQgf6QgRyAhABSABCDgoMZGF0YWJhc2VfcmVmQg4KDF9kZXNjcmlwdGlvbiJtCgpUZXN0UmVzdWx0Eg4KBnJ1bl9pZBgBIAEoCRIlCgR0ZXN0GAIgASgLMg0uc3Ryb3BweS5UZXN0Qgj6QgWKAQIQARIYCgtncmFmYW5hX3VybBgDIAEoCUgAiAEBQg4KDF9ncmFmYW5hX3VybCIpCglUZXN0U3VpdGUSHAoFdGVzdHMYASADKAsyDS5zdHJvcHB5LlRlc3QibgoPVGVzdFN1aXRlUmVzdWx0EisKBXN1aXRlGAIgASgLMhIuc3Ryb3BweS5UZXN0U3VpdGVCCPpCBYoBAhABEi4KB3Jlc3VsdHMYAyADKAsyEy5zdHJvcHB5LlRlc3RSZXN1bHRCCPpCBZIBAggBIqsBCgtSdW5TZXR0aW5ncxIXCgZydW5faWQYASABKAlCB/pCBHICEAESLAoGdGFyZ2V0GAIgASgOMhIuZGVwbG95bWVudC5UYXJnZXRCCPpCBYIBAhABEi4KCHNldHRpbmdzGAMgASgLMhIuc2V0dGluZ3MuU2V0dGluZ3NCCPpCBYoBAhABEiUKBHRlc3QYBCABKAsyDS5zdHJvcHB5LlRlc3RCCPpCBYoBAhABQj9aPWdpdGh1Yi5jb20vc3Ryb3BweS1pby9oYXRjaGV0LXdvcmtmbG93L2ludGVybmFsL3Byb3RvL3N0cm9wcHliBnByb3RvMw", [file_database_database, file_deployment_deployment, file_google_protobuf_duration, file_settings_settings, file_validate_validate]);

/**
 * @generated from message stroppy.StroppyCli
 */
export type StroppyCli = Message<"stroppy.StroppyCli"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: string binary_path = 2;
   */
  binaryPath: string;

  /**
   * @generated from field: string workdir = 3;
   */
  workdir: string;

  /**
   * @generated from field: stroppy.StroppyCli.Workload workload = 4;
   */
  workload: StroppyCli_Workload;

  /**
   * @generated from field: optional uint32 scale_factor = 5;
   */
  scaleFactor?: number;

  /**
   * @generated from field: optional google.protobuf.Duration duration = 6;
   */
  duration?: Duration;

  /**
   * @generated from field: map<string, string> stroppy_env = 7;
   */
  stroppyEnv: { [key: string]: string };
};

/**
 * @generated from message stroppy.StroppyCli
 */
export type StroppyCliJson = {
  /**
   * @generated from field: string version = 1;
   */
  version?: string;

  /**
   * @generated from field: string binary_path = 2;
   */
  binaryPath?: string;

  /**
   * @generated from field: string workdir = 3;
   */
  workdir?: string;

  /**
   * @generated from field: stroppy.StroppyCli.Workload workload = 4;
   */
  workload?: StroppyCli_WorkloadJson;

  /**
   * @generated from field: optional uint32 scale_factor = 5;
   */
  scaleFactor?: number;

  /**
   * @generated from field: optional google.protobuf.Duration duration = 6;
   */
  duration?: DurationJson;

  /**
   * @generated from field: map<string, string> stroppy_env = 7;
   */
  stroppyEnv?: { [key: string]: string };
};

export type StroppyCliValid = StroppyCli;

/**
 * Describes the message stroppy.StroppyCli.
 * Use `create(StroppyCliSchema)` to create a new message.
 */
export const StroppyCliSchema: GenMessage<StroppyCli, {jsonType: StroppyCliJson, validType: StroppyCliValid}> = /*@__PURE__*/
  messageDesc(file_stroppy_test, 0);

/**
 * @generated from enum stroppy.StroppyCli.Workload
 */
export enum StroppyCli_Workload {
  /**
   * @generated from enum value: WORKLOAD_UNSPECIFIED = 0;
   */
  WORKLOAD_UNSPECIFIED = 0,

  /**
   * @generated from enum value: TPCC = 1;
   */
  TPCC = 1,

  /**
   * @generated from enum value: TPCB = 2;
   */
  TPCB = 2,
}

/**
 * @generated from enum stroppy.StroppyCli.Workload
 */
export type StroppyCli_WorkloadJson = "WORKLOAD_UNSPECIFIED" | "TPCC" | "TPCB";

/**
 * Describes the enum stroppy.StroppyCli.Workload.
 */
export const StroppyCli_WorkloadSchema: GenEnum<StroppyCli_Workload, StroppyCli_WorkloadJson> = /*@__PURE__*/
  enumDesc(file_stroppy_test, 0, 0);

/**
 * @generated from message stroppy.Test
 */
export type Test = Message<"stroppy.Test"> & {
  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: stroppy.StroppyCli stroppy_cli = 4;
   */
  stroppyCli?: StroppyCli;

  /**
   * @generated from field: deployment.Hardware stroppy_hardware = 7;
   */
  stroppyHardware?: Hardware;

  /**
   * @generated from oneof stroppy.Test.database_ref
   */
  databaseRef: {
    /**
     * @generated from field: database.Database.Template database_template = 101;
     */
    value: Database_Template;
    case: "databaseTemplate";
  } | {
    /**
     * @generated from field: string connection_string = 102;
     */
    value: string;
    case: "connectionString";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message stroppy.Test
 */
export type TestJson = {
  /**
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: stroppy.StroppyCli stroppy_cli = 4;
   */
  stroppyCli?: StroppyCliJson;

  /**
   * @generated from field: deployment.Hardware stroppy_hardware = 7;
   */
  stroppyHardware?: HardwareJson;

  /**
   * @generated from field: database.Database.Template database_template = 101;
   */
  databaseTemplate?: Database_TemplateJson;

  /**
   * @generated from field: string connection_string = 102;
   */
  connectionString?: string;
};

export type TestValid = Test;

/**
 * Describes the message stroppy.Test.
 * Use `create(TestSchema)` to create a new message.
 */
export const TestSchema: GenMessage<Test, {jsonType: TestJson, validType: TestValid}> = /*@__PURE__*/
  messageDesc(file_stroppy_test, 1);

/**
 * @generated from message stroppy.TestResult
 */
export type TestResult = Message<"stroppy.TestResult"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * @generated from field: stroppy.Test test = 2;
   */
  test?: Test;

  /**
   * @generated from field: optional string grafana_url = 3;
   */
  grafanaUrl?: string;
};

/**
 * @generated from message stroppy.TestResult
 */
export type TestResultJson = {
  /**
   * @generated from field: string run_id = 1;
   */
  runId?: string;

  /**
   * @generated from field: stroppy.Test test = 2;
   */
  test?: TestJson;

  /**
   * @generated from field: optional string grafana_url = 3;
   */
  grafanaUrl?: string;
};

export type TestResultValid = TestResult;

/**
 * Describes the message stroppy.TestResult.
 * Use `create(TestResultSchema)` to create a new message.
 */
export const TestResultSchema: GenMessage<TestResult, {jsonType: TestResultJson, validType: TestResultValid}> = /*@__PURE__*/
  messageDesc(file_stroppy_test, 2);

/**
 * @generated from message stroppy.TestSuite
 */
export type TestSuite = Message<"stroppy.TestSuite"> & {
  /**
   * @generated from field: repeated stroppy.Test tests = 1;
   */
  tests: Test[];
};

/**
 * @generated from message stroppy.TestSuite
 */
export type TestSuiteJson = {
  /**
   * @generated from field: repeated stroppy.Test tests = 1;
   */
  tests?: TestJson[];
};

export type TestSuiteValid = TestSuite;

/**
 * Describes the message stroppy.TestSuite.
 * Use `create(TestSuiteSchema)` to create a new message.
 */
export const TestSuiteSchema: GenMessage<TestSuite, {jsonType: TestSuiteJson, validType: TestSuiteValid}> = /*@__PURE__*/
  messageDesc(file_stroppy_test, 3);

/**
 * @generated from message stroppy.TestSuiteResult
 */
export type TestSuiteResult = Message<"stroppy.TestSuiteResult"> & {
  /**
   * @generated from field: stroppy.TestSuite suite = 2;
   */
  suite?: TestSuite;

  /**
   * @generated from field: repeated stroppy.TestResult results = 3;
   */
  results: TestResult[];
};

/**
 * @generated from message stroppy.TestSuiteResult
 */
export type TestSuiteResultJson = {
  /**
   * @generated from field: stroppy.TestSuite suite = 2;
   */
  suite?: TestSuiteJson;

  /**
   * @generated from field: repeated stroppy.TestResult results = 3;
   */
  results?: TestResultJson[];
};

export type TestSuiteResultValid = TestSuiteResult;

/**
 * Describes the message stroppy.TestSuiteResult.
 * Use `create(TestSuiteResultSchema)` to create a new message.
 */
export const TestSuiteResultSchema: GenMessage<TestSuiteResult, {jsonType: TestSuiteResultJson, validType: TestSuiteResultValid}> = /*@__PURE__*/
  messageDesc(file_stroppy_test, 4);

/**
 * @generated from message stroppy.RunSettings
 */
export type RunSettings = Message<"stroppy.RunSettings"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * @generated from field: deployment.Target target = 2;
   */
  target: Target;

  /**
   * @generated from field: settings.Settings settings = 3;
   */
  settings?: Settings;

  /**
   * @generated from field: stroppy.Test test = 4;
   */
  test?: Test;
};

/**
 * @generated from message stroppy.RunSettings
 */
export type RunSettingsJson = {
  /**
   * @generated from field: string run_id = 1;
   */
  runId?: string;

  /**
   * @generated from field: deployment.Target target = 2;
   */
  target?: TargetJson;

  /**
   * @generated from field: settings.Settings settings = 3;
   */
  settings?: SettingsJson;

  /**
   * @generated from field: stroppy.Test test = 4;
   */
  test?: TestJson;
};

export type RunSettingsValid = RunSettings;

/**
 * Describes the message stroppy.RunSettings.
 * Use `create(RunSettingsSchema)` to create a new message.
 */
export const RunSettingsSchema: GenMessage<RunSettings, {jsonType: RunSettingsJson, validType: RunSettingsValid}> = /*@__PURE__*/
  messageDesc(file_stroppy_test, 5);

