// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=ts,json_types=true,valid_types=legacy_required+protovalidate_required"
// @generated from file goplain/goplain.proto (package goplain, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Field, Field_Cardinality, Field_CardinalityJson, Field_Kind, Field_KindJson, FieldJson, FieldOptions as FieldOptions$1, FileOptions as FileOptions$1, MessageOptions as MessageOptions$1, OneofOptions as OneofOptions$1, Type, TypeJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor, file_google_protobuf_type } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file goplain/goplain.proto.
 */
export const file_goplain_goplain: GenFile = /*@__PURE__*/
  fileDesc("ChVnb3BsYWluL2dvcGxhaW4ucHJvdG8SB2dvcGxhaW4iLAoHR29JZGVudBIMCgRuYW1lGAEgASgJEhMKC2ltcG9ydF9wYXRoGAIgASgJIpUCChBPdmVycmlkZVNlbGVjdG9yEh0KEHRhcmdldF9mdWxsX3BhdGgYASABKAlIAIgBARI0CgpmaWVsZF9raW5kGAIgASgOMhsuZ29vZ2xlLnByb3RvYnVmLkZpZWxkLktpbmRIAYgBARJCChFmaWVsZF9jYXJkaW5hbGl0eRgDIAEoDjIiLmdvb2dsZS5wcm90b2J1Zi5GaWVsZC5DYXJkaW5hbGl0eUgCiAEBEhsKDmZpZWxkX3R5cGVfdXJsGAQgASgJSAOIAQFCEwoRX3RhcmdldF9mdWxsX3BhdGhCDQoLX2ZpZWxkX2tpbmRCFAoSX2ZpZWxkX2NhcmRpbmFsaXR5QhEKD19maWVsZF90eXBlX3VybCJlCgxUeXBlT3ZlcnJpZGUSKwoIc2VsZWN0b3IYASABKAsyGS5nb3BsYWluLk92ZXJyaWRlU2VsZWN0b3ISKAoOdGFyZ2V0X2dvX3R5cGUYAiABKAsyEC5nb3BsYWluLkdvSWRlbnQigAEKDk1lc3NhZ2VPcHRpb25zEhAKCGdlbmVyYXRlGAEgASgIEhIKCnR5cGVfYWxpYXMYAiABKAgSGAoQdHlwZV9hbGlhc19maWVsZBgDIAEoCRIuCg52aXJ0dWFsX2ZpZWxkcxgEIAMoCzIWLmdvb2dsZS5wcm90b2J1Zi5GaWVsZCJuCgtGaWxlT3B0aW9ucxIxChJnb190eXBlc19vdmVycmlkZXMYASADKAsyFS5nb3BsYWluLlR5cGVPdmVycmlkZRIsCg12aXJ0dWFsX3R5cGVzGAIgAygLMhUuZ29vZ2xlLnByb3RvYnVmLlR5cGUiuAEKDEZpZWxkT3B0aW9ucxInCg1vdmVycmlkZV90eXBlGAEgASgLMhAuZ29wbGFpbi5Hb0lkZW50EhEKCXNlcmlhbGl6ZRgCIAEoCBINCgVlbWJlZBgEIAEoCBIZChFlbWJlZF93aXRoX3ByZWZpeBgFIAEoCBIWCg5lbnVtX2FzX3N0cmluZxgHIAEoCBITCgtlbnVtX2FzX2ludBgIIAEoCBIVCg13cml0ZV9kZWZhdWx0GAkgASgIIjgKDE9uZW9mT3B0aW9ucxINCgVlbWJlZBgBIAEoCBIZChFlbWJlZF93aXRoX3ByZWZpeBgCIAEoCDpICgRmaWxlEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGODUAyABKAsyFC5nb3BsYWluLkZpbGVPcHRpb25zUgRmaWxlOlQKB21lc3NhZ2USHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY4NQDIAEoCzIXLmdvcGxhaW4uTWVzc2FnZU9wdGlvbnNSB21lc3NhZ2U6TAoFZmllbGQSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGODUAyABKAsyFS5nb3BsYWluLkZpZWxkT3B0aW9uc1IFZmllbGQ6TAoFb25lb2YSHS5nb29nbGUucHJvdG9idWYuT25lb2ZPcHRpb25zGNCGAyABKAsyFS5nb3BsYWluLk9uZW9mT3B0aW9uc1IFb25lb2ZCMFouZ2l0aHViLmNvbS95YXJvaGVyL3Byb3RvYy1nZW4tZ28tcGxhaW4vZ29wbGFpbmIGcHJvdG8z", [file_google_protobuf_descriptor, file_google_protobuf_type]);

/**
 * @generated from message goplain.GoIdent
 */
export type GoIdent = Message<"goplain.GoIdent"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string import_path = 2;
   */
  importPath: string;
};

/**
 * @generated from message goplain.GoIdent
 */
export type GoIdentJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: string import_path = 2;
   */
  importPath?: string;
};

export type GoIdentValid = GoIdent;

/**
 * Describes the message goplain.GoIdent.
 * Use `create(GoIdentSchema)` to create a new message.
 */
export const GoIdentSchema: GenMessage<GoIdent, {jsonType: GoIdentJson, validType: GoIdentValid}> = /*@__PURE__*/
  messageDesc(file_goplain_goplain, 0);

/**
 * @generated from message goplain.OverrideSelector
 */
export type OverrideSelector = Message<"goplain.OverrideSelector"> & {
  /**
   * @generated from field: optional string target_full_path = 1;
   */
  targetFullPath?: string;

  /**
   * from google.protobuf.Field
   *
   * @generated from field: optional google.protobuf.Field.Kind field_kind = 2;
   */
  fieldKind?: Field_Kind;

  /**
   * @generated from field: optional google.protobuf.Field.Cardinality field_cardinality = 3;
   */
  fieldCardinality?: Field_Cardinality;

  /**
   * @generated from field: optional string field_type_url = 4;
   */
  fieldTypeUrl?: string;
};

/**
 * @generated from message goplain.OverrideSelector
 */
export type OverrideSelectorJson = {
  /**
   * @generated from field: optional string target_full_path = 1;
   */
  targetFullPath?: string;

  /**
   * from google.protobuf.Field
   *
   * @generated from field: optional google.protobuf.Field.Kind field_kind = 2;
   */
  fieldKind?: Field_KindJson;

  /**
   * @generated from field: optional google.protobuf.Field.Cardinality field_cardinality = 3;
   */
  fieldCardinality?: Field_CardinalityJson;

  /**
   * @generated from field: optional string field_type_url = 4;
   */
  fieldTypeUrl?: string;
};

export type OverrideSelectorValid = OverrideSelector;

/**
 * Describes the message goplain.OverrideSelector.
 * Use `create(OverrideSelectorSchema)` to create a new message.
 */
export const OverrideSelectorSchema: GenMessage<OverrideSelector, {jsonType: OverrideSelectorJson, validType: OverrideSelectorValid}> = /*@__PURE__*/
  messageDesc(file_goplain_goplain, 1);

/**
 * @generated from message goplain.TypeOverride
 */
export type TypeOverride = Message<"goplain.TypeOverride"> & {
  /**
   * @generated from field: goplain.OverrideSelector selector = 1;
   */
  selector?: OverrideSelector;

  /**
   * If types are not directly compatible, casters will be requested
   * as parameters to IntoPlain/IntoPb methods using cast.Caster[A,B] interface
   *
   * @generated from field: goplain.GoIdent target_go_type = 2;
   */
  targetGoType?: GoIdent;
};

/**
 * @generated from message goplain.TypeOverride
 */
export type TypeOverrideJson = {
  /**
   * @generated from field: goplain.OverrideSelector selector = 1;
   */
  selector?: OverrideSelectorJson;

  /**
   * If types are not directly compatible, casters will be requested
   * as parameters to IntoPlain/IntoPb methods using cast.Caster[A,B] interface
   *
   * @generated from field: goplain.GoIdent target_go_type = 2;
   */
  targetGoType?: GoIdentJson;
};

export type TypeOverrideValid = TypeOverride;

/**
 * Describes the message goplain.TypeOverride.
 * Use `create(TypeOverrideSchema)` to create a new message.
 */
export const TypeOverrideSchema: GenMessage<TypeOverride, {jsonType: TypeOverrideJson, validType: TypeOverrideValid}> = /*@__PURE__*/
  messageDesc(file_goplain_goplain, 2);

/**
 * @generated from message goplain.MessageOptions
 */
export type MessageOptions = Message<"goplain.MessageOptions"> & {
  /**
   * @generated from field: bool generate = 1;
   */
  generate: boolean;

  /**
   *
   * Type alias instead of message.
   * This means that this message has one field named "<scalar_type> value"
   * example:
   * message Int32Alias {
   * option (plain.field).type_alias = true;
   * int32 value = 1;
   * }
   * // this:
   * message Int32AliasUSAGE {
   * Int32Alias value = 1;
   * }
   * // becomes:
   * message Int32AliasUSAGE {
   * int32 value = 1;
   * }
   *
   * @generated from field: bool type_alias = 2;
   */
  typeAlias: boolean;

  /**
   * @generated from field: string type_alias_field = 3;
   */
  typeAliasField: string;

  /**
   *
   * Virtual fields for this message.
   * Number is filled automatically.
   * This does not affect the original message numbers alignment cause this field does not apply to the original message.
   * Needs only to included in plain message and use in final code with plain messages.
   * Example:
   * message User {
   * (plain.message).virtual_fields = [
   * {name: "password_hash", kind: TYPE_STRING}
   * ];
   * string name = 1;
   * }
   * // becomes:
   * message UserPlain {
   * string name = 1;
   * string password_hash = 2;
   * }
   *
   * @generated from field: repeated google.protobuf.Field virtual_fields = 4;
   */
  virtualFields: Field[];
};

/**
 * @generated from message goplain.MessageOptions
 */
export type MessageOptionsJson = {
  /**
   * @generated from field: bool generate = 1;
   */
  generate?: boolean;

  /**
   *
   * Type alias instead of message.
   * This means that this message has one field named "<scalar_type> value"
   * example:
   * message Int32Alias {
   * option (plain.field).type_alias = true;
   * int32 value = 1;
   * }
   * // this:
   * message Int32AliasUSAGE {
   * Int32Alias value = 1;
   * }
   * // becomes:
   * message Int32AliasUSAGE {
   * int32 value = 1;
   * }
   *
   * @generated from field: bool type_alias = 2;
   */
  typeAlias?: boolean;

  /**
   * @generated from field: string type_alias_field = 3;
   */
  typeAliasField?: string;

  /**
   *
   * Virtual fields for this message.
   * Number is filled automatically.
   * This does not affect the original message numbers alignment cause this field does not apply to the original message.
   * Needs only to included in plain message and use in final code with plain messages.
   * Example:
   * message User {
   * (plain.message).virtual_fields = [
   * {name: "password_hash", kind: TYPE_STRING}
   * ];
   * string name = 1;
   * }
   * // becomes:
   * message UserPlain {
   * string name = 1;
   * string password_hash = 2;
   * }
   *
   * @generated from field: repeated google.protobuf.Field virtual_fields = 4;
   */
  virtualFields?: FieldJson[];
};

export type MessageOptionsValid = MessageOptions;

/**
 * Describes the message goplain.MessageOptions.
 * Use `create(MessageOptionsSchema)` to create a new message.
 */
export const MessageOptionsSchema: GenMessage<MessageOptions, {jsonType: MessageOptionsJson, validType: MessageOptionsValid}> = /*@__PURE__*/
  messageDesc(file_goplain_goplain, 3);

/**
 * @generated from message goplain.FileOptions
 */
export type FileOptions = Message<"goplain.FileOptions"> & {
  /**
   * @generated from field: repeated goplain.TypeOverride go_types_overrides = 1;
   */
  goTypesOverrides: TypeOverride[];

  /**
   * @generated from field: repeated google.protobuf.Type virtual_types = 2;
   */
  virtualTypes: Type[];
};

/**
 * @generated from message goplain.FileOptions
 */
export type FileOptionsJson = {
  /**
   * @generated from field: repeated goplain.TypeOverride go_types_overrides = 1;
   */
  goTypesOverrides?: TypeOverrideJson[];

  /**
   * @generated from field: repeated google.protobuf.Type virtual_types = 2;
   */
  virtualTypes?: TypeJson[];
};

export type FileOptionsValid = FileOptions;

/**
 * Describes the message goplain.FileOptions.
 * Use `create(FileOptionsSchema)` to create a new message.
 */
export const FileOptionsSchema: GenMessage<FileOptions, {jsonType: FileOptionsJson, validType: FileOptionsValid}> = /*@__PURE__*/
  messageDesc(file_goplain_goplain, 4);

/**
 * @generated from message goplain.FieldOptions
 */
export type FieldOptions = Message<"goplain.FieldOptions"> & {
  /**
   * @generated from field: goplain.GoIdent override_type = 1;
   */
  overrideType?: GoIdent;

  /**
   *
   * Field serialization options.
   * If set to true, the field will be serialized as a JSON object.
   *
   * Example:
   * message User {
   * string name = 1;
   * Address address = 2 [(goplain.field).serialized = true];
   * repeated Address addresses = 3 [(goplain.field).serialized = true];
   * }
   *
   * Becomes:
   * message UserPlain {
   * string name = 1;
   *
   * // without prefix:
   * bytes address = 2;
   * repeated bytes addresses = 3;
   * }
   *
   * @generated from field: bool serialize = 2;
   */
  serialize: boolean;

  /**
   *
   * Embed field into parent message
   *
   * Example:
   * message Address {
   * string street = 1;
   * }
   * message User {
   * string name = 1;
   * Address address = 2 [(goplain.field).embed = {with_prefix: true}];
   * }
   *
   * Becomes:
   * message UserPlain {
   * string name = 1;
   *
   * // without prefix:
   * string street = 2;
   *
   * // or with prefix:
   * string address_street = 3;
   * }
   *
   * @generated from field: bool embed = 4;
   */
  embed: boolean;

  /**
   * @generated from field: bool embed_with_prefix = 5;
   */
  embedWithPrefix: boolean;

  /**
   * @generated from field: bool enum_as_string = 7;
   */
  enumAsString: boolean;

  /**
   * @generated from field: bool enum_as_int = 8;
   */
  enumAsInt: boolean;

  /**
   * If true, write field to JSON even if it has default/zero value
   * Default behavior (false): omit fields with default values from JSON
   *
   * @generated from field: bool write_default = 9;
   */
  writeDefault: boolean;
};

/**
 * @generated from message goplain.FieldOptions
 */
export type FieldOptionsJson = {
  /**
   * @generated from field: goplain.GoIdent override_type = 1;
   */
  overrideType?: GoIdentJson;

  /**
   *
   * Field serialization options.
   * If set to true, the field will be serialized as a JSON object.
   *
   * Example:
   * message User {
   * string name = 1;
   * Address address = 2 [(goplain.field).serialized = true];
   * repeated Address addresses = 3 [(goplain.field).serialized = true];
   * }
   *
   * Becomes:
   * message UserPlain {
   * string name = 1;
   *
   * // without prefix:
   * bytes address = 2;
   * repeated bytes addresses = 3;
   * }
   *
   * @generated from field: bool serialize = 2;
   */
  serialize?: boolean;

  /**
   *
   * Embed field into parent message
   *
   * Example:
   * message Address {
   * string street = 1;
   * }
   * message User {
   * string name = 1;
   * Address address = 2 [(goplain.field).embed = {with_prefix: true}];
   * }
   *
   * Becomes:
   * message UserPlain {
   * string name = 1;
   *
   * // without prefix:
   * string street = 2;
   *
   * // or with prefix:
   * string address_street = 3;
   * }
   *
   * @generated from field: bool embed = 4;
   */
  embed?: boolean;

  /**
   * @generated from field: bool embed_with_prefix = 5;
   */
  embedWithPrefix?: boolean;

  /**
   * @generated from field: bool enum_as_string = 7;
   */
  enumAsString?: boolean;

  /**
   * @generated from field: bool enum_as_int = 8;
   */
  enumAsInt?: boolean;

  /**
   * If true, write field to JSON even if it has default/zero value
   * Default behavior (false): omit fields with default values from JSON
   *
   * @generated from field: bool write_default = 9;
   */
  writeDefault?: boolean;
};

export type FieldOptionsValid = FieldOptions;

/**
 * Describes the message goplain.FieldOptions.
 * Use `create(FieldOptionsSchema)` to create a new message.
 */
export const FieldOptionsSchema: GenMessage<FieldOptions, {jsonType: FieldOptionsJson, validType: FieldOptionsValid}> = /*@__PURE__*/
  messageDesc(file_goplain_goplain, 5);

/**
 * @generated from message goplain.OneofOptions
 */
export type OneofOptions = Message<"goplain.OneofOptions"> & {
  /**
   *
   * Embed oneof into parent message
   *
   * Example:
   * message User {
   * string name = 1;
   * oneof address {
   * (goplain.oneof).embed = true;
   * Address address = 2;
   * string street = 3;
   * }
   * }
   *
   * Becomes:
   * message UserPlain {
   * string name = 1;
   *
   * // without prefix:
   * Address address = 2;
   * string street = 3;
   *
   * // or with prefix:
   * Address address_address = 4;
   * string address_street = 5;
   * }
   *
   * only meanfull for go-plain structs (not protoc-gen-go)
   *
   * @generated from field: bool embed = 1;
   */
  embed: boolean;

  /**
   * @generated from field: bool embed_with_prefix = 2;
   */
  embedWithPrefix: boolean;
};

/**
 * @generated from message goplain.OneofOptions
 */
export type OneofOptionsJson = {
  /**
   *
   * Embed oneof into parent message
   *
   * Example:
   * message User {
   * string name = 1;
   * oneof address {
   * (goplain.oneof).embed = true;
   * Address address = 2;
   * string street = 3;
   * }
   * }
   *
   * Becomes:
   * message UserPlain {
   * string name = 1;
   *
   * // without prefix:
   * Address address = 2;
   * string street = 3;
   *
   * // or with prefix:
   * Address address_address = 4;
   * string address_street = 5;
   * }
   *
   * only meanfull for go-plain structs (not protoc-gen-go)
   *
   * @generated from field: bool embed = 1;
   */
  embed?: boolean;

  /**
   * @generated from field: bool embed_with_prefix = 2;
   */
  embedWithPrefix?: boolean;
};

export type OneofOptionsValid = OneofOptions;

/**
 * Describes the message goplain.OneofOptions.
 * Use `create(OneofOptionsSchema)` to create a new message.
 */
export const OneofOptionsSchema: GenMessage<OneofOptions, {jsonType: OneofOptionsJson, validType: OneofOptionsValid}> = /*@__PURE__*/
  messageDesc(file_goplain_goplain, 6);

/**
 * @generated from extension: goplain.FileOptions file = 60000;
 */
export const file: GenExtension<FileOptions$1, FileOptions> = /*@__PURE__*/
  extDesc(file_goplain_goplain, 0);

/**
 * @generated from extension: goplain.MessageOptions message = 60000;
 */
export const message: GenExtension<MessageOptions$1, MessageOptions> = /*@__PURE__*/
  extDesc(file_goplain_goplain, 1);

/**
 * @generated from extension: goplain.FieldOptions field = 60000;
 */
export const field: GenExtension<FieldOptions$1, FieldOptions> = /*@__PURE__*/
  extDesc(file_goplain_goplain, 2);

/**
 * @generated from extension: goplain.OneofOptions oneof = 50000;
 */
export const oneof: GenExtension<OneofOptions$1, OneofOptions> = /*@__PURE__*/
  extDesc(file_goplain_goplain, 3);

