// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: models/domain.proto

package models

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SettingsRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SettingsRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SettingsRecord with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SettingsRecordMultiError,
// or nil if none found.
func (m *SettingsRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *SettingsRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Data

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SettingsRecordValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SettingsRecordValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SettingsRecordValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SettingsRecordMultiError(errors)
	}

	return nil
}

// SettingsRecordMultiError is an error wrapping multiple validation errors
// returned by SettingsRecord.ValidateAll() if the designated constraints
// aren't met.
type SettingsRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SettingsRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SettingsRecordMultiError) AllErrors() []error { return m }

// SettingsRecordValidationError is the validation error returned by
// SettingsRecord.Validate if the designated constraints aren't met.
type SettingsRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SettingsRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SettingsRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SettingsRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SettingsRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SettingsRecordValidationError) ErrorName() string { return "SettingsRecordValidationError" }

// Error satisfies the builtin error interface
func (e SettingsRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSettingsRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SettingsRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SettingsRecordValidationError{}

// Validate checks the field values on SuiteRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SuiteRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SuiteRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SuiteRecordMultiError, or
// nil if none found.
func (m *SuiteRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *SuiteRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	// no validation rules for Target

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SuiteRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SuiteRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SuiteRecordValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.HatchetRunId != nil {
		// no validation rules for HatchetRunId
	}

	if m.TestSuite != nil {
		// no validation rules for TestSuite
	}

	if m.StartedAt != nil {

		if all {
			switch v := interface{}(m.GetStartedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SuiteRecordValidationError{
						field:  "StartedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SuiteRecordValidationError{
						field:  "StartedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SuiteRecordValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.FinishedAt != nil {

		if all {
			switch v := interface{}(m.GetFinishedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SuiteRecordValidationError{
						field:  "FinishedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SuiteRecordValidationError{
						field:  "FinishedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFinishedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SuiteRecordValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DurationMs != nil {
		// no validation rules for DurationMs
	}

	if m.ErrorMessage != nil {
		// no validation rules for ErrorMessage
	}

	if m.Results != nil {
		// no validation rules for Results
	}

	if len(errors) > 0 {
		return SuiteRecordMultiError(errors)
	}

	return nil
}

// SuiteRecordMultiError is an error wrapping multiple validation errors
// returned by SuiteRecord.ValidateAll() if the designated constraints aren't met.
type SuiteRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SuiteRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SuiteRecordMultiError) AllErrors() []error { return m }

// SuiteRecordValidationError is the validation error returned by
// SuiteRecord.Validate if the designated constraints aren't met.
type SuiteRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SuiteRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SuiteRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SuiteRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SuiteRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SuiteRecordValidationError) ErrorName() string { return "SuiteRecordValidationError" }

// Error satisfies the builtin error interface
func (e SuiteRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSuiteRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SuiteRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SuiteRecordValidationError{}

// Validate checks the field values on RunRecord with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RunRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RunRecordMultiError, or nil
// if none found.
func (m *RunRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *RunRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SuiteId

	// no validation rules for Status

	// no validation rules for Target

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunRecordValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.HatchetRunId != nil {
		// no validation rules for HatchetRunId
	}

	if m.Test != nil {
		// no validation rules for Test
	}

	if m.StartedAt != nil {

		if all {
			switch v := interface{}(m.GetStartedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RunRecordValidationError{
						field:  "StartedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RunRecordValidationError{
						field:  "StartedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RunRecordValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.FinishedAt != nil {

		if all {
			switch v := interface{}(m.GetFinishedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RunRecordValidationError{
						field:  "FinishedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RunRecordValidationError{
						field:  "FinishedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFinishedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RunRecordValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.DurationMs != nil {
		// no validation rules for DurationMs
	}

	if m.ErrorMessage != nil {
		// no validation rules for ErrorMessage
	}

	if m.Dag != nil {
		// no validation rules for Dag
	}

	if m.Results != nil {
		// no validation rules for Results
	}

	if len(errors) > 0 {
		return RunRecordMultiError(errors)
	}

	return nil
}

// RunRecordMultiError is an error wrapping multiple validation errors returned
// by RunRecord.ValidateAll() if the designated constraints aren't met.
type RunRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunRecordMultiError) AllErrors() []error { return m }

// RunRecordValidationError is the validation error returned by
// RunRecord.Validate if the designated constraints aren't met.
type RunRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunRecordValidationError) ErrorName() string { return "RunRecordValidationError" }

// Error satisfies the builtin error interface
func (e RunRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunRecordValidationError{}

// Validate checks the field values on TopologyTemplateRecord with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TopologyTemplateRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TopologyTemplateRecord with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TopologyTemplateRecordMultiError, or nil if none found.
func (m *TopologyTemplateRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *TopologyTemplateRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for DatabaseType

	// no validation rules for Builtin

	// no validation rules for TemplateData

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TopologyTemplateRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TopologyTemplateRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TopologyTemplateRecordValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TopologyTemplateRecordValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TopologyTemplateRecordValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TopologyTemplateRecordValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return TopologyTemplateRecordMultiError(errors)
	}

	return nil
}

// TopologyTemplateRecordMultiError is an error wrapping multiple validation
// errors returned by TopologyTemplateRecord.ValidateAll() if the designated
// constraints aren't met.
type TopologyTemplateRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TopologyTemplateRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TopologyTemplateRecordMultiError) AllErrors() []error { return m }

// TopologyTemplateRecordValidationError is the validation error returned by
// TopologyTemplateRecord.Validate if the designated constraints aren't met.
type TopologyTemplateRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TopologyTemplateRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TopologyTemplateRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TopologyTemplateRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TopologyTemplateRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TopologyTemplateRecordValidationError) ErrorName() string {
	return "TopologyTemplateRecordValidationError"
}

// Error satisfies the builtin error interface
func (e TopologyTemplateRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTopologyTemplateRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TopologyTemplateRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TopologyTemplateRecordValidationError{}

// Validate checks the field values on WorkloadRecord with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WorkloadRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkloadRecord with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WorkloadRecordMultiError,
// or nil if none found.
func (m *WorkloadRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkloadRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Builtin

	// no validation rules for Script

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkloadRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkloadRecordValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkloadRecordValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if m.SqlData != nil {
		// no validation rules for SqlData
	}

	if m.Probe != nil {
		// no validation rules for Probe
	}

	if len(errors) > 0 {
		return WorkloadRecordMultiError(errors)
	}

	return nil
}

// WorkloadRecordMultiError is an error wrapping multiple validation errors
// returned by WorkloadRecord.ValidateAll() if the designated constraints
// aren't met.
type WorkloadRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkloadRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkloadRecordMultiError) AllErrors() []error { return m }

// WorkloadRecordValidationError is the validation error returned by
// WorkloadRecord.Validate if the designated constraints aren't met.
type WorkloadRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkloadRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkloadRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkloadRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkloadRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkloadRecordValidationError) ErrorName() string { return "WorkloadRecordValidationError" }

// Error satisfies the builtin error interface
func (e WorkloadRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkloadRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkloadRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkloadRecordValidationError{}
