// Code generated by protoc-gen-ratel. DO NOT EDIT.
// source: models/domain.proto

package models

import (
	"errors"
	"time"

	"github.com/yaroher/ratel/pkg/ddl"
	"github.com/yaroher/ratel/pkg/dml/set"
	"github.com/yaroher/ratel/pkg/exec"
	"github.com/yaroher/ratel/pkg/pgx-ext/sqlerr"
	"github.com/yaroher/ratel/pkg/repository"
	"github.com/yaroher/ratel/pkg/schema"
)

var (
	_ = time.Time{}
	_ = errors.New
	_ = sqlerr.IsConstraintNamed
)

// SettingsRecordAlias is the table alias type for the settings table
type SettingsRecordAlias string

func (a SettingsRecordAlias) String() string { return string(a) }

const SettingsRecordAliasName SettingsRecordAlias = "settings"

// SettingsRecordColumnAlias represents column names for the settings table
type SettingsRecordColumnAlias string

func (c SettingsRecordColumnAlias) String() string { return string(c) }

const (
	SettingsRecordColumnId        SettingsRecordColumnAlias = "id"
	SettingsRecordColumnData      SettingsRecordColumnAlias = "data"
	SettingsRecordColumnUpdatedAt SettingsRecordColumnAlias = "updated_at"
)

func (s *SettingsRecordScanner) GetTarget(col string) func() any {
	switch SettingsRecordColumnAlias(col) {
	case SettingsRecordColumnId:
		return func() any { return &s.Id }
	case SettingsRecordColumnData:
		return func() any { return &s.Data }
	case SettingsRecordColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	default:
		panic("unknown field: " + col)
	}
}

func (s *SettingsRecordScanner) GetSetter(f SettingsRecordColumnAlias) func() set.ValueSetter[SettingsRecordColumnAlias] {
	switch f {
	case SettingsRecordColumnId:
		return func() set.ValueSetter[SettingsRecordColumnAlias] { return set.NewSetter(f, &s.Id) }
	case SettingsRecordColumnData:
		return func() set.ValueSetter[SettingsRecordColumnAlias] { return set.NewSetter(f, &s.Data) }
	case SettingsRecordColumnUpdatedAt:
		return func() set.ValueSetter[SettingsRecordColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *SettingsRecordScanner) GetValue(f SettingsRecordColumnAlias) func() any {
	switch f {
	case SettingsRecordColumnId:
		return func() any { return s.Id }
	case SettingsRecordColumnData:
		return func() any { return s.Data }
	case SettingsRecordColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the settings table
func (s *SettingsRecordScanner) Relations() []exec.RelationLoader[*SettingsRecordScanner] {
	return nil
}

// SettingsRecordsTable represents the settings table with its columns
type SettingsRecordsTable struct {
	*schema.Table[SettingsRecordAlias, SettingsRecordColumnAlias, *SettingsRecordScanner]
	Id        schema.TextColumnI[SettingsRecordColumnAlias]
	Data      schema.ByteaColumnI[SettingsRecordColumnAlias]
	UpdatedAt schema.TimestamptzColumnI[SettingsRecordColumnAlias]
}

// SettingsRecords is the global settings table instance
var SettingsRecords = func() SettingsRecordsTable {
	idCol := schema.TextColumn(SettingsRecordColumnId, ddl.WithPrimaryKey[SettingsRecordColumnAlias](), ddl.WithDefault[SettingsRecordColumnAlias]("'default'"))
	dataCol := schema.ByteaColumn(SettingsRecordColumnData, ddl.WithDefault[SettingsRecordColumnAlias]("'{}'"))
	updatedAtCol := schema.TimestamptzColumn(SettingsRecordColumnUpdatedAt, ddl.WithDefault[SettingsRecordColumnAlias]("now()"))

	return SettingsRecordsTable{
		Table: schema.NewTable[SettingsRecordAlias, SettingsRecordColumnAlias, *SettingsRecordScanner](
			SettingsRecordAliasName,
			func() *SettingsRecordScanner { return &SettingsRecordScanner{} },
			[]*ddl.ColumnDDL[SettingsRecordColumnAlias]{
				idCol.DDL(),
				dataCol.DDL(),
				updatedAtCol.DDL(),
			},
		),
		Id:        idCol,
		Data:      dataCol,
		UpdatedAt: updatedAtCol,
	}
}()

// SettingsRecordsRef is a reference to the settings table for relations
var SettingsRecordsRef schema.RelationTableAlias[SettingsRecordAlias] = SettingsRecords.Table

// SettingsRecordConverter provides conversion between SettingsRecord and SettingsRecordScanner
var SettingsRecordConverter = repository.Converter[*SettingsRecordScanner, *SettingsRecord]{
	ToScanner: (*SettingsRecord).IntoPlain,
	ToProto:   (*SettingsRecordScanner).IntoPb,
}

// SuiteRecordAlias is the table alias type for the suites table
type SuiteRecordAlias string

func (a SuiteRecordAlias) String() string { return string(a) }

const SuiteRecordAliasName SuiteRecordAlias = "suites"

// SuiteRecordColumnAlias represents column names for the suites table
type SuiteRecordColumnAlias string

func (c SuiteRecordColumnAlias) String() string { return string(c) }

const (
	SuiteRecordColumnId           SuiteRecordColumnAlias = "id"
	SuiteRecordColumnHatchetRunId SuiteRecordColumnAlias = "hatchet_run_id"
	SuiteRecordColumnStatus       SuiteRecordColumnAlias = "status"
	SuiteRecordColumnTestSuite    SuiteRecordColumnAlias = "test_suite"
	SuiteRecordColumnTarget       SuiteRecordColumnAlias = "target"
	SuiteRecordColumnCreatedAt    SuiteRecordColumnAlias = "created_at"
	SuiteRecordColumnStartedAt    SuiteRecordColumnAlias = "started_at"
	SuiteRecordColumnFinishedAt   SuiteRecordColumnAlias = "finished_at"
	SuiteRecordColumnDurationMs   SuiteRecordColumnAlias = "duration_ms"
	SuiteRecordColumnErrorMessage SuiteRecordColumnAlias = "error_message"
	SuiteRecordColumnResults      SuiteRecordColumnAlias = "results"
)

func (s *SuiteRecordScanner) GetTarget(col string) func() any {
	switch SuiteRecordColumnAlias(col) {
	case SuiteRecordColumnId:
		return func() any { return &s.Id }
	case SuiteRecordColumnHatchetRunId:
		return func() any { return &s.HatchetRunId }
	case SuiteRecordColumnStatus:
		return func() any { return &s.Status }
	case SuiteRecordColumnTestSuite:
		return func() any { return &s.TestSuite }
	case SuiteRecordColumnTarget:
		return func() any { return &s.Target }
	case SuiteRecordColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case SuiteRecordColumnStartedAt:
		return func() any { return &s.StartedAt }
	case SuiteRecordColumnFinishedAt:
		return func() any { return &s.FinishedAt }
	case SuiteRecordColumnDurationMs:
		return func() any { return &s.DurationMs }
	case SuiteRecordColumnErrorMessage:
		return func() any { return &s.ErrorMessage }
	case SuiteRecordColumnResults:
		return func() any { return &s.Results }
	default:
		panic("unknown field: " + col)
	}
}

func (s *SuiteRecordScanner) GetSetter(f SuiteRecordColumnAlias) func() set.ValueSetter[SuiteRecordColumnAlias] {
	switch f {
	case SuiteRecordColumnId:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.Id) }
	case SuiteRecordColumnHatchetRunId:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.HatchetRunId) }
	case SuiteRecordColumnStatus:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.Status) }
	case SuiteRecordColumnTestSuite:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.TestSuite) }
	case SuiteRecordColumnTarget:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.Target) }
	case SuiteRecordColumnCreatedAt:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case SuiteRecordColumnStartedAt:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.StartedAt) }
	case SuiteRecordColumnFinishedAt:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.FinishedAt) }
	case SuiteRecordColumnDurationMs:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.DurationMs) }
	case SuiteRecordColumnErrorMessage:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.ErrorMessage) }
	case SuiteRecordColumnResults:
		return func() set.ValueSetter[SuiteRecordColumnAlias] { return set.NewSetter(f, &s.Results) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *SuiteRecordScanner) GetValue(f SuiteRecordColumnAlias) func() any {
	switch f {
	case SuiteRecordColumnId:
		return func() any { return s.Id }
	case SuiteRecordColumnHatchetRunId:
		return func() any { return s.HatchetRunId }
	case SuiteRecordColumnStatus:
		return func() any { return s.Status }
	case SuiteRecordColumnTestSuite:
		return func() any { return s.TestSuite }
	case SuiteRecordColumnTarget:
		return func() any { return s.Target }
	case SuiteRecordColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case SuiteRecordColumnStartedAt:
		return func() any { return s.StartedAt }
	case SuiteRecordColumnFinishedAt:
		return func() any { return s.FinishedAt }
	case SuiteRecordColumnDurationMs:
		return func() any { return s.DurationMs }
	case SuiteRecordColumnErrorMessage:
		return func() any { return s.ErrorMessage }
	case SuiteRecordColumnResults:
		return func() any { return s.Results }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the suites table
func (s *SuiteRecordScanner) Relations() []exec.RelationLoader[*SuiteRecordScanner] {
	return nil
}

// SuiteRecordsTable represents the suites table with its columns
type SuiteRecordsTable struct {
	*schema.Table[SuiteRecordAlias, SuiteRecordColumnAlias, *SuiteRecordScanner]
	Id           schema.TextColumnI[SuiteRecordColumnAlias]
	HatchetRunId schema.TextColumnI[SuiteRecordColumnAlias]
	Status       schema.IntegerColumnI[SuiteRecordColumnAlias]
	TestSuite    schema.ByteaColumnI[SuiteRecordColumnAlias]
	Target       schema.IntegerColumnI[SuiteRecordColumnAlias]
	CreatedAt    schema.TimestamptzColumnI[SuiteRecordColumnAlias]
	StartedAt    schema.TimestamptzColumnI[SuiteRecordColumnAlias]
	FinishedAt   schema.TimestamptzColumnI[SuiteRecordColumnAlias]
	DurationMs   schema.BigIntColumnI[SuiteRecordColumnAlias]
	ErrorMessage schema.TextColumnI[SuiteRecordColumnAlias]
	Results      schema.ByteaColumnI[SuiteRecordColumnAlias]
}

// SuiteRecords is the global suites table instance
var SuiteRecords = func() SuiteRecordsTable {
	idCol := schema.TextColumn(SuiteRecordColumnId, ddl.WithPrimaryKey[SuiteRecordColumnAlias]())
	hatchetRunIdCol := schema.TextColumn(SuiteRecordColumnHatchetRunId)
	statusCol := schema.IntegerColumn(SuiteRecordColumnStatus, ddl.WithDefault[SuiteRecordColumnAlias]("0"))
	testSuiteCol := schema.ByteaColumn(SuiteRecordColumnTestSuite)
	targetCol := schema.IntegerColumn(SuiteRecordColumnTarget, ddl.WithDefault[SuiteRecordColumnAlias]("0"))
	createdAtCol := schema.TimestamptzColumn(SuiteRecordColumnCreatedAt, ddl.WithDefault[SuiteRecordColumnAlias]("now()"))
	startedAtCol := schema.TimestamptzColumn(SuiteRecordColumnStartedAt)
	finishedAtCol := schema.TimestamptzColumn(SuiteRecordColumnFinishedAt)
	durationMsCol := schema.BigIntColumn(SuiteRecordColumnDurationMs)
	errorMessageCol := schema.TextColumn(SuiteRecordColumnErrorMessage)
	resultsCol := schema.ByteaColumn(SuiteRecordColumnResults)

	idx0 := ddl.NewIndex[SuiteRecordAlias, SuiteRecordColumnAlias]("idx_suites_status", SuiteRecordAliasName).OnColumns(SuiteRecordColumnStatus)
	idx1 := ddl.NewIndex[SuiteRecordAlias, SuiteRecordColumnAlias]("idx_suites_created_at", SuiteRecordAliasName).OnColumns(SuiteRecordColumnCreatedAt)

	return SuiteRecordsTable{
		Table: schema.NewTable[SuiteRecordAlias, SuiteRecordColumnAlias, *SuiteRecordScanner](
			SuiteRecordAliasName,
			func() *SuiteRecordScanner { return &SuiteRecordScanner{} },
			[]*ddl.ColumnDDL[SuiteRecordColumnAlias]{
				idCol.DDL(),
				hatchetRunIdCol.DDL(),
				statusCol.DDL(),
				testSuiteCol.DDL(),
				targetCol.DDL(),
				createdAtCol.DDL(),
				startedAtCol.DDL(),
				finishedAtCol.DDL(),
				durationMsCol.DDL(),
				errorMessageCol.DDL(),
				resultsCol.DDL(),
			},
			ddl.WithIndexes[SuiteRecordAlias, SuiteRecordColumnAlias](
				idx0,
				idx1,
			),
		),
		Id:           idCol,
		HatchetRunId: hatchetRunIdCol,
		Status:       statusCol,
		TestSuite:    testSuiteCol,
		Target:       targetCol,
		CreatedAt:    createdAtCol,
		StartedAt:    startedAtCol,
		FinishedAt:   finishedAtCol,
		DurationMs:   durationMsCol,
		ErrorMessage: errorMessageCol,
		Results:      resultsCol,
	}
}()

// SuiteRecordsRef is a reference to the suites table for relations
var SuiteRecordsRef schema.RelationTableAlias[SuiteRecordAlias] = SuiteRecords.Table

// SuiteRecordConverter provides conversion between SuiteRecord and SuiteRecordScanner
var SuiteRecordConverter = repository.Converter[*SuiteRecordScanner, *SuiteRecord]{
	ToScanner: (*SuiteRecord).IntoPlain,
	ToProto:   (*SuiteRecordScanner).IntoPb,
}

// RunRecordAlias is the table alias type for the runs table
type RunRecordAlias string

func (a RunRecordAlias) String() string { return string(a) }

const RunRecordAliasName RunRecordAlias = "runs"

// RunRecordColumnAlias represents column names for the runs table
type RunRecordColumnAlias string

func (c RunRecordColumnAlias) String() string { return string(c) }

const (
	RunRecordColumnId           RunRecordColumnAlias = "id"
	RunRecordColumnSuiteId      RunRecordColumnAlias = "suite_id"
	RunRecordColumnHatchetRunId RunRecordColumnAlias = "hatchet_run_id"
	RunRecordColumnStatus       RunRecordColumnAlias = "status"
	RunRecordColumnTest         RunRecordColumnAlias = "test"
	RunRecordColumnTarget       RunRecordColumnAlias = "target"
	RunRecordColumnCreatedAt    RunRecordColumnAlias = "created_at"
	RunRecordColumnStartedAt    RunRecordColumnAlias = "started_at"
	RunRecordColumnFinishedAt   RunRecordColumnAlias = "finished_at"
	RunRecordColumnDurationMs   RunRecordColumnAlias = "duration_ms"
	RunRecordColumnErrorMessage RunRecordColumnAlias = "error_message"
	RunRecordColumnDag          RunRecordColumnAlias = "dag"
	RunRecordColumnResults      RunRecordColumnAlias = "results"
)

func (s *RunRecordScanner) GetTarget(col string) func() any {
	switch RunRecordColumnAlias(col) {
	case RunRecordColumnId:
		return func() any { return &s.Id }
	case RunRecordColumnSuiteId:
		return func() any { return &s.SuiteId }
	case RunRecordColumnHatchetRunId:
		return func() any { return &s.HatchetRunId }
	case RunRecordColumnStatus:
		return func() any { return &s.Status }
	case RunRecordColumnTest:
		return func() any { return &s.Test }
	case RunRecordColumnTarget:
		return func() any { return &s.Target }
	case RunRecordColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case RunRecordColumnStartedAt:
		return func() any { return &s.StartedAt }
	case RunRecordColumnFinishedAt:
		return func() any { return &s.FinishedAt }
	case RunRecordColumnDurationMs:
		return func() any { return &s.DurationMs }
	case RunRecordColumnErrorMessage:
		return func() any { return &s.ErrorMessage }
	case RunRecordColumnDag:
		return func() any { return &s.Dag }
	case RunRecordColumnResults:
		return func() any { return &s.Results }
	default:
		panic("unknown field: " + col)
	}
}

func (s *RunRecordScanner) GetSetter(f RunRecordColumnAlias) func() set.ValueSetter[RunRecordColumnAlias] {
	switch f {
	case RunRecordColumnId:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.Id) }
	case RunRecordColumnSuiteId:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.SuiteId) }
	case RunRecordColumnHatchetRunId:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.HatchetRunId) }
	case RunRecordColumnStatus:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.Status) }
	case RunRecordColumnTest:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.Test) }
	case RunRecordColumnTarget:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.Target) }
	case RunRecordColumnCreatedAt:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case RunRecordColumnStartedAt:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.StartedAt) }
	case RunRecordColumnFinishedAt:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.FinishedAt) }
	case RunRecordColumnDurationMs:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.DurationMs) }
	case RunRecordColumnErrorMessage:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.ErrorMessage) }
	case RunRecordColumnDag:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.Dag) }
	case RunRecordColumnResults:
		return func() set.ValueSetter[RunRecordColumnAlias] { return set.NewSetter(f, &s.Results) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *RunRecordScanner) GetValue(f RunRecordColumnAlias) func() any {
	switch f {
	case RunRecordColumnId:
		return func() any { return s.Id }
	case RunRecordColumnSuiteId:
		return func() any { return s.SuiteId }
	case RunRecordColumnHatchetRunId:
		return func() any { return s.HatchetRunId }
	case RunRecordColumnStatus:
		return func() any { return s.Status }
	case RunRecordColumnTest:
		return func() any { return s.Test }
	case RunRecordColumnTarget:
		return func() any { return s.Target }
	case RunRecordColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case RunRecordColumnStartedAt:
		return func() any { return s.StartedAt }
	case RunRecordColumnFinishedAt:
		return func() any { return s.FinishedAt }
	case RunRecordColumnDurationMs:
		return func() any { return s.DurationMs }
	case RunRecordColumnErrorMessage:
		return func() any { return s.ErrorMessage }
	case RunRecordColumnDag:
		return func() any { return s.Dag }
	case RunRecordColumnResults:
		return func() any { return s.Results }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the runs table
func (s *RunRecordScanner) Relations() []exec.RelationLoader[*RunRecordScanner] {
	return nil
}

// RunRecordsTable represents the runs table with its columns
type RunRecordsTable struct {
	*schema.Table[RunRecordAlias, RunRecordColumnAlias, *RunRecordScanner]
	Id           schema.TextColumnI[RunRecordColumnAlias]
	SuiteId      schema.TextColumnI[RunRecordColumnAlias]
	HatchetRunId schema.TextColumnI[RunRecordColumnAlias]
	Status       schema.IntegerColumnI[RunRecordColumnAlias]
	Test         schema.ByteaColumnI[RunRecordColumnAlias]
	Target       schema.IntegerColumnI[RunRecordColumnAlias]
	CreatedAt    schema.TimestamptzColumnI[RunRecordColumnAlias]
	StartedAt    schema.TimestamptzColumnI[RunRecordColumnAlias]
	FinishedAt   schema.TimestamptzColumnI[RunRecordColumnAlias]
	DurationMs   schema.BigIntColumnI[RunRecordColumnAlias]
	ErrorMessage schema.TextColumnI[RunRecordColumnAlias]
	Dag          schema.ByteaColumnI[RunRecordColumnAlias]
	Results      schema.ByteaColumnI[RunRecordColumnAlias]
}

// RunRecords is the global runs table instance
var RunRecords = func() RunRecordsTable {
	idCol := schema.TextColumn(RunRecordColumnId, ddl.WithPrimaryKey[RunRecordColumnAlias]())
	suiteIdCol := schema.TextColumn(RunRecordColumnSuiteId)
	hatchetRunIdCol := schema.TextColumn(RunRecordColumnHatchetRunId)
	statusCol := schema.IntegerColumn(RunRecordColumnStatus, ddl.WithDefault[RunRecordColumnAlias]("0"))
	testCol := schema.ByteaColumn(RunRecordColumnTest)
	targetCol := schema.IntegerColumn(RunRecordColumnTarget, ddl.WithDefault[RunRecordColumnAlias]("0"))
	createdAtCol := schema.TimestamptzColumn(RunRecordColumnCreatedAt, ddl.WithDefault[RunRecordColumnAlias]("now()"))
	startedAtCol := schema.TimestamptzColumn(RunRecordColumnStartedAt)
	finishedAtCol := schema.TimestamptzColumn(RunRecordColumnFinishedAt)
	durationMsCol := schema.BigIntColumn(RunRecordColumnDurationMs)
	errorMessageCol := schema.TextColumn(RunRecordColumnErrorMessage)
	dagCol := schema.ByteaColumn(RunRecordColumnDag)
	resultsCol := schema.ByteaColumn(RunRecordColumnResults)

	idx0 := ddl.NewIndex[RunRecordAlias, RunRecordColumnAlias]("idx_runs_suite_id", RunRecordAliasName).OnColumns(RunRecordColumnSuiteId)
	idx1 := ddl.NewIndex[RunRecordAlias, RunRecordColumnAlias]("idx_runs_status", RunRecordAliasName).OnColumns(RunRecordColumnStatus)
	idx2 := ddl.NewIndex[RunRecordAlias, RunRecordColumnAlias]("idx_runs_created_at", RunRecordAliasName).OnColumns(RunRecordColumnCreatedAt)
	idx3 := ddl.NewIndex[RunRecordAlias, RunRecordColumnAlias]("idx_runs_hatchet_run_id", RunRecordAliasName).OnColumns(RunRecordColumnHatchetRunId)

	return RunRecordsTable{
		Table: schema.NewTable[RunRecordAlias, RunRecordColumnAlias, *RunRecordScanner](
			RunRecordAliasName,
			func() *RunRecordScanner { return &RunRecordScanner{} },
			[]*ddl.ColumnDDL[RunRecordColumnAlias]{
				idCol.DDL(),
				suiteIdCol.DDL(),
				hatchetRunIdCol.DDL(),
				statusCol.DDL(),
				testCol.DDL(),
				targetCol.DDL(),
				createdAtCol.DDL(),
				startedAtCol.DDL(),
				finishedAtCol.DDL(),
				durationMsCol.DDL(),
				errorMessageCol.DDL(),
				dagCol.DDL(),
				resultsCol.DDL(),
			},
			ddl.WithIndexes[RunRecordAlias, RunRecordColumnAlias](
				idx0,
				idx1,
				idx2,
				idx3,
			),
		),
		Id:           idCol,
		SuiteId:      suiteIdCol,
		HatchetRunId: hatchetRunIdCol,
		Status:       statusCol,
		Test:         testCol,
		Target:       targetCol,
		CreatedAt:    createdAtCol,
		StartedAt:    startedAtCol,
		FinishedAt:   finishedAtCol,
		DurationMs:   durationMsCol,
		ErrorMessage: errorMessageCol,
		Dag:          dagCol,
		Results:      resultsCol,
	}
}()

// RunRecordsRef is a reference to the runs table for relations
var RunRecordsRef schema.RelationTableAlias[RunRecordAlias] = RunRecords.Table

// RunRecordConverter provides conversion between RunRecord and RunRecordScanner
var RunRecordConverter = repository.Converter[*RunRecordScanner, *RunRecord]{
	ToScanner: (*RunRecord).IntoPlain,
	ToProto:   (*RunRecordScanner).IntoPb,
}

// TopologyTemplateRecordAlias is the table alias type for the topology_templates table
type TopologyTemplateRecordAlias string

func (a TopologyTemplateRecordAlias) String() string { return string(a) }

const TopologyTemplateRecordAliasName TopologyTemplateRecordAlias = "topology_templates"

// TopologyTemplateRecordColumnAlias represents column names for the topology_templates table
type TopologyTemplateRecordColumnAlias string

func (c TopologyTemplateRecordColumnAlias) String() string { return string(c) }

const (
	TopologyTemplateRecordColumnId           TopologyTemplateRecordColumnAlias = "id"
	TopologyTemplateRecordColumnName         TopologyTemplateRecordColumnAlias = "name"
	TopologyTemplateRecordColumnDescription  TopologyTemplateRecordColumnAlias = "description"
	TopologyTemplateRecordColumnDatabaseType TopologyTemplateRecordColumnAlias = "database_type"
	TopologyTemplateRecordColumnBuiltin      TopologyTemplateRecordColumnAlias = "builtin"
	TopologyTemplateRecordColumnTemplateData TopologyTemplateRecordColumnAlias = "template_data"
	TopologyTemplateRecordColumnCreatedAt    TopologyTemplateRecordColumnAlias = "created_at"
	TopologyTemplateRecordColumnUpdatedAt    TopologyTemplateRecordColumnAlias = "updated_at"
)

func (s *TopologyTemplateRecordScanner) GetTarget(col string) func() any {
	switch TopologyTemplateRecordColumnAlias(col) {
	case TopologyTemplateRecordColumnId:
		return func() any { return &s.Id }
	case TopologyTemplateRecordColumnName:
		return func() any { return &s.Name }
	case TopologyTemplateRecordColumnDescription:
		return func() any { return &s.Description }
	case TopologyTemplateRecordColumnDatabaseType:
		return func() any { return &s.DatabaseType }
	case TopologyTemplateRecordColumnBuiltin:
		return func() any { return &s.Builtin }
	case TopologyTemplateRecordColumnTemplateData:
		return func() any { return &s.TemplateData }
	case TopologyTemplateRecordColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case TopologyTemplateRecordColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	default:
		panic("unknown field: " + col)
	}
}

func (s *TopologyTemplateRecordScanner) GetSetter(f TopologyTemplateRecordColumnAlias) func() set.ValueSetter[TopologyTemplateRecordColumnAlias] {
	switch f {
	case TopologyTemplateRecordColumnId:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.Id) }
	case TopologyTemplateRecordColumnName:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.Name) }
	case TopologyTemplateRecordColumnDescription:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.Description) }
	case TopologyTemplateRecordColumnDatabaseType:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.DatabaseType) }
	case TopologyTemplateRecordColumnBuiltin:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.Builtin) }
	case TopologyTemplateRecordColumnTemplateData:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.TemplateData) }
	case TopologyTemplateRecordColumnCreatedAt:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case TopologyTemplateRecordColumnUpdatedAt:
		return func() set.ValueSetter[TopologyTemplateRecordColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *TopologyTemplateRecordScanner) GetValue(f TopologyTemplateRecordColumnAlias) func() any {
	switch f {
	case TopologyTemplateRecordColumnId:
		return func() any { return s.Id }
	case TopologyTemplateRecordColumnName:
		return func() any { return s.Name }
	case TopologyTemplateRecordColumnDescription:
		return func() any { return s.Description }
	case TopologyTemplateRecordColumnDatabaseType:
		return func() any { return s.DatabaseType }
	case TopologyTemplateRecordColumnBuiltin:
		return func() any { return s.Builtin }
	case TopologyTemplateRecordColumnTemplateData:
		return func() any { return s.TemplateData }
	case TopologyTemplateRecordColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case TopologyTemplateRecordColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the topology_templates table
func (s *TopologyTemplateRecordScanner) Relations() []exec.RelationLoader[*TopologyTemplateRecordScanner] {
	return nil
}

// TopologyTemplateRecordsTable represents the topology_templates table with its columns
type TopologyTemplateRecordsTable struct {
	*schema.Table[TopologyTemplateRecordAlias, TopologyTemplateRecordColumnAlias, *TopologyTemplateRecordScanner]
	Id           schema.TextColumnI[TopologyTemplateRecordColumnAlias]
	Name         schema.TextColumnI[TopologyTemplateRecordColumnAlias]
	Description  schema.TextColumnI[TopologyTemplateRecordColumnAlias]
	DatabaseType schema.IntegerColumnI[TopologyTemplateRecordColumnAlias]
	Builtin      schema.BooleanColumnI[TopologyTemplateRecordColumnAlias]
	TemplateData schema.ByteaColumnI[TopologyTemplateRecordColumnAlias]
	CreatedAt    schema.TimestamptzColumnI[TopologyTemplateRecordColumnAlias]
	UpdatedAt    schema.TimestamptzColumnI[TopologyTemplateRecordColumnAlias]
}

// TopologyTemplateRecords is the global topology_templates table instance
var TopologyTemplateRecords = func() TopologyTemplateRecordsTable {
	idCol := schema.TextColumn(TopologyTemplateRecordColumnId, ddl.WithPrimaryKey[TopologyTemplateRecordColumnAlias]())
	nameCol := schema.TextColumn(TopologyTemplateRecordColumnName)
	descriptionCol := schema.TextColumn(TopologyTemplateRecordColumnDescription)
	databaseTypeCol := schema.IntegerColumn(TopologyTemplateRecordColumnDatabaseType, ddl.WithDefault[TopologyTemplateRecordColumnAlias]("0"))
	builtinCol := schema.BooleanColumn(TopologyTemplateRecordColumnBuiltin, ddl.WithDefault[TopologyTemplateRecordColumnAlias]("false"))
	templateDataCol := schema.ByteaColumn(TopologyTemplateRecordColumnTemplateData)
	createdAtCol := schema.TimestamptzColumn(TopologyTemplateRecordColumnCreatedAt, ddl.WithDefault[TopologyTemplateRecordColumnAlias]("now()"))
	updatedAtCol := schema.TimestamptzColumn(TopologyTemplateRecordColumnUpdatedAt, ddl.WithDefault[TopologyTemplateRecordColumnAlias]("now()"))

	idx0 := ddl.NewIndex[TopologyTemplateRecordAlias, TopologyTemplateRecordColumnAlias]("idx_topology_templates_name", TopologyTemplateRecordAliasName).OnColumns(TopologyTemplateRecordColumnName)
	idx0 = idx0.Unique()
	idx1 := ddl.NewIndex[TopologyTemplateRecordAlias, TopologyTemplateRecordColumnAlias]("idx_topology_templates_database_type", TopologyTemplateRecordAliasName).OnColumns(TopologyTemplateRecordColumnDatabaseType)

	return TopologyTemplateRecordsTable{
		Table: schema.NewTable[TopologyTemplateRecordAlias, TopologyTemplateRecordColumnAlias, *TopologyTemplateRecordScanner](
			TopologyTemplateRecordAliasName,
			func() *TopologyTemplateRecordScanner { return &TopologyTemplateRecordScanner{} },
			[]*ddl.ColumnDDL[TopologyTemplateRecordColumnAlias]{
				idCol.DDL(),
				nameCol.DDL(),
				descriptionCol.DDL(),
				databaseTypeCol.DDL(),
				builtinCol.DDL(),
				templateDataCol.DDL(),
				createdAtCol.DDL(),
				updatedAtCol.DDL(),
			},
			ddl.WithIndexes[TopologyTemplateRecordAlias, TopologyTemplateRecordColumnAlias](
				idx0,
				idx1,
			),
		),
		Id:           idCol,
		Name:         nameCol,
		Description:  descriptionCol,
		DatabaseType: databaseTypeCol,
		Builtin:      builtinCol,
		TemplateData: templateDataCol,
		CreatedAt:    createdAtCol,
		UpdatedAt:    updatedAtCol,
	}
}()

// TopologyTemplateRecordsRef is a reference to the topology_templates table for relations
var TopologyTemplateRecordsRef schema.RelationTableAlias[TopologyTemplateRecordAlias] = TopologyTemplateRecords.Table

// TopologyTemplateRecordConverter provides conversion between TopologyTemplateRecord and TopologyTemplateRecordScanner
var TopologyTemplateRecordConverter = repository.Converter[*TopologyTemplateRecordScanner, *TopologyTemplateRecord]{
	ToScanner: (*TopologyTemplateRecord).IntoPlain,
	ToProto:   (*TopologyTemplateRecordScanner).IntoPb,
}

// WorkloadRecordAlias is the table alias type for the workloads table
type WorkloadRecordAlias string

func (a WorkloadRecordAlias) String() string { return string(a) }

const WorkloadRecordAliasName WorkloadRecordAlias = "workloads"

// WorkloadRecordColumnAlias represents column names for the workloads table
type WorkloadRecordColumnAlias string

func (c WorkloadRecordColumnAlias) String() string { return string(c) }

const (
	WorkloadRecordColumnId          WorkloadRecordColumnAlias = "id"
	WorkloadRecordColumnName        WorkloadRecordColumnAlias = "name"
	WorkloadRecordColumnDescription WorkloadRecordColumnAlias = "description"
	WorkloadRecordColumnBuiltin     WorkloadRecordColumnAlias = "builtin"
	WorkloadRecordColumnScript      WorkloadRecordColumnAlias = "script"
	WorkloadRecordColumnSqlData     WorkloadRecordColumnAlias = "sql_data"
	WorkloadRecordColumnProbe       WorkloadRecordColumnAlias = "probe"
	WorkloadRecordColumnCreatedAt   WorkloadRecordColumnAlias = "created_at"
)

func (s *WorkloadRecordScanner) GetTarget(col string) func() any {
	switch WorkloadRecordColumnAlias(col) {
	case WorkloadRecordColumnId:
		return func() any { return &s.Id }
	case WorkloadRecordColumnName:
		return func() any { return &s.Name }
	case WorkloadRecordColumnDescription:
		return func() any { return &s.Description }
	case WorkloadRecordColumnBuiltin:
		return func() any { return &s.Builtin }
	case WorkloadRecordColumnScript:
		return func() any { return &s.Script }
	case WorkloadRecordColumnSqlData:
		return func() any { return &s.SqlData }
	case WorkloadRecordColumnProbe:
		return func() any { return &s.Probe }
	case WorkloadRecordColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	default:
		panic("unknown field: " + col)
	}
}

func (s *WorkloadRecordScanner) GetSetter(f WorkloadRecordColumnAlias) func() set.ValueSetter[WorkloadRecordColumnAlias] {
	switch f {
	case WorkloadRecordColumnId:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.Id) }
	case WorkloadRecordColumnName:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.Name) }
	case WorkloadRecordColumnDescription:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.Description) }
	case WorkloadRecordColumnBuiltin:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.Builtin) }
	case WorkloadRecordColumnScript:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.Script) }
	case WorkloadRecordColumnSqlData:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.SqlData) }
	case WorkloadRecordColumnProbe:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.Probe) }
	case WorkloadRecordColumnCreatedAt:
		return func() set.ValueSetter[WorkloadRecordColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *WorkloadRecordScanner) GetValue(f WorkloadRecordColumnAlias) func() any {
	switch f {
	case WorkloadRecordColumnId:
		return func() any { return s.Id }
	case WorkloadRecordColumnName:
		return func() any { return s.Name }
	case WorkloadRecordColumnDescription:
		return func() any { return s.Description }
	case WorkloadRecordColumnBuiltin:
		return func() any { return s.Builtin }
	case WorkloadRecordColumnScript:
		return func() any { return s.Script }
	case WorkloadRecordColumnSqlData:
		return func() any { return s.SqlData }
	case WorkloadRecordColumnProbe:
		return func() any { return s.Probe }
	case WorkloadRecordColumnCreatedAt:
		return func() any { return s.CreatedAt }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the workloads table
func (s *WorkloadRecordScanner) Relations() []exec.RelationLoader[*WorkloadRecordScanner] {
	return nil
}

// WorkloadRecordsTable represents the workloads table with its columns
type WorkloadRecordsTable struct {
	*schema.Table[WorkloadRecordAlias, WorkloadRecordColumnAlias, *WorkloadRecordScanner]
	Id          schema.TextColumnI[WorkloadRecordColumnAlias]
	Name        schema.TextColumnI[WorkloadRecordColumnAlias]
	Description schema.TextColumnI[WorkloadRecordColumnAlias]
	Builtin     schema.BooleanColumnI[WorkloadRecordColumnAlias]
	Script      schema.ByteaColumnI[WorkloadRecordColumnAlias]
	SqlData     schema.ByteaColumnI[WorkloadRecordColumnAlias]
	Probe       schema.ByteaColumnI[WorkloadRecordColumnAlias]
	CreatedAt   schema.TimestamptzColumnI[WorkloadRecordColumnAlias]
}

// WorkloadRecords is the global workloads table instance
var WorkloadRecords = func() WorkloadRecordsTable {
	idCol := schema.TextColumn(WorkloadRecordColumnId, ddl.WithPrimaryKey[WorkloadRecordColumnAlias]())
	nameCol := schema.TextColumn(WorkloadRecordColumnName)
	descriptionCol := schema.TextColumn(WorkloadRecordColumnDescription)
	builtinCol := schema.BooleanColumn(WorkloadRecordColumnBuiltin, ddl.WithDefault[WorkloadRecordColumnAlias]("false"))
	scriptCol := schema.ByteaColumn(WorkloadRecordColumnScript)
	sqlDataCol := schema.ByteaColumn(WorkloadRecordColumnSqlData)
	probeCol := schema.ByteaColumn(WorkloadRecordColumnProbe)
	createdAtCol := schema.TimestamptzColumn(WorkloadRecordColumnCreatedAt, ddl.WithDefault[WorkloadRecordColumnAlias]("now()"))

	idx0 := ddl.NewIndex[WorkloadRecordAlias, WorkloadRecordColumnAlias]("idx_workloads_name", WorkloadRecordAliasName).OnColumns(WorkloadRecordColumnName)
	idx0 = idx0.Unique()

	return WorkloadRecordsTable{
		Table: schema.NewTable[WorkloadRecordAlias, WorkloadRecordColumnAlias, *WorkloadRecordScanner](
			WorkloadRecordAliasName,
			func() *WorkloadRecordScanner { return &WorkloadRecordScanner{} },
			[]*ddl.ColumnDDL[WorkloadRecordColumnAlias]{
				idCol.DDL(),
				nameCol.DDL(),
				descriptionCol.DDL(),
				builtinCol.DDL(),
				scriptCol.DDL(),
				sqlDataCol.DDL(),
				probeCol.DDL(),
				createdAtCol.DDL(),
			},
			ddl.WithIndexes[WorkloadRecordAlias, WorkloadRecordColumnAlias](
				idx0,
			),
		),
		Id:          idCol,
		Name:        nameCol,
		Description: descriptionCol,
		Builtin:     builtinCol,
		Script:      scriptCol,
		SqlData:     sqlDataCol,
		Probe:       probeCol,
		CreatedAt:   createdAtCol,
	}
}()

// WorkloadRecordsRef is a reference to the workloads table for relations
var WorkloadRecordsRef schema.RelationTableAlias[WorkloadRecordAlias] = WorkloadRecords.Table

// WorkloadRecordConverter provides conversion between WorkloadRecord and WorkloadRecordScanner
var WorkloadRecordConverter = repository.Converter[*WorkloadRecordScanner, *WorkloadRecord]{
	ToScanner: (*WorkloadRecord).IntoPlain,
	ToProto:   (*WorkloadRecordScanner).IntoPb,
}

// ============================================================================
// Constraint Names
// ============================================================================

const (
	SettingsRecordConstraintPkey            = "settings_pkey"
	SuiteRecordConstraintPkey               = "suites_pkey"
	RunRecordConstraintPkey                 = "runs_pkey"
	TopologyTemplateRecordConstraintPkey    = "topology_templates_pkey"
	TopologyTemplateRecordConstraintNameIdx = "idx_topology_templates_name"
	WorkloadRecordConstraintPkey            = "workloads_pkey"
	WorkloadRecordConstraintNameIdx         = "idx_workloads_name"
)

// ============================================================================
// Constraint Errors
// ============================================================================

var (
	ErrSettingsRecordPrimaryKey            = errors.New("primary key constraint violated: settings_pkey")
	ErrSuiteRecordPrimaryKey               = errors.New("primary key constraint violated: suites_pkey")
	ErrRunRecordPrimaryKey                 = errors.New("primary key constraint violated: runs_pkey")
	ErrTopologyTemplateRecordPrimaryKey    = errors.New("primary key constraint violated: topology_templates_pkey")
	ErrTopologyTemplateRecordNameUniqueIdx = errors.New("unique constraint violated: idx_topology_templates_name")
	ErrWorkloadRecordPrimaryKey            = errors.New("primary key constraint violated: workloads_pkey")
	ErrWorkloadRecordNameUniqueIdx         = errors.New("unique constraint violated: idx_workloads_name")
)

// ============================================================================
// Constraint Error Check Functions
// ============================================================================

// IsSettingsRecordPrimaryKeyError checks if the error is a primary_key constraint violation on settings
func IsSettingsRecordPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, SettingsRecordConstraintPkey)
}

// IsSuiteRecordPrimaryKeyError checks if the error is a primary_key constraint violation on suites
func IsSuiteRecordPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, SuiteRecordConstraintPkey)
}

// IsRunRecordPrimaryKeyError checks if the error is a primary_key constraint violation on runs
func IsRunRecordPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, RunRecordConstraintPkey)
}

// IsTopologyTemplateRecordPrimaryKeyError checks if the error is a primary_key constraint violation on topology_templates
func IsTopologyTemplateRecordPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, TopologyTemplateRecordConstraintPkey)
}

// IsTopologyTemplateRecordNameUniqueIdxError checks if the error is a unique constraint violation on topology_templates
func IsTopologyTemplateRecordNameUniqueIdxError(err error) bool {
	return sqlerr.IsConstraintNamed(err, TopologyTemplateRecordConstraintNameIdx)
}

// IsWorkloadRecordPrimaryKeyError checks if the error is a primary_key constraint violation on workloads
func IsWorkloadRecordPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, WorkloadRecordConstraintPkey)
}

// IsWorkloadRecordNameUniqueIdxError checks if the error is a unique constraint violation on workloads
func IsWorkloadRecordNameUniqueIdxError(err error) bool {
	return sqlerr.IsConstraintNamed(err, WorkloadRecordConstraintNameIdx)
}
