// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=ts,json_types=true,valid_types=legacy_required+protovalidate_required"
// @generated from file edge/edge.proto (package edge, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_validate_validate } from "../validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file edge/edge.proto.
 */
export const file_edge_edge: GenFile = /*@__PURE__*/
  fileDesc("Cg9lZGdlL2VkZ2UucHJvdG8SBGVkZ2UiwAEKBldvcmtlchIcCgt3b3JrZXJfbmFtZRgBIAEoCUIH+kIEcgIQARI5ChBhY2NlcHRhYmxlX3Rhc2tzGAIgAygLMhUuZWRnZS5UYXNrLklkZW50aWZpZXJCCPpCBZIBAggBEiwKCG1ldGFkYXRhGAYgAygLMhouZWRnZS5Xb3JrZXIuTWV0YWRhdGFFbnRyeRovCg1NZXRhZGF0YUVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEi2QEKBFRhc2saaAoKSWRlbnRpZmllchIXCgZydW5faWQYASABKAlCB/pCBHICEAESGAoHdGFza19pZBgCIAEoCUIH+kIEcgIQARInCgRraW5kGAMgASgOMg8uZWRnZS5UYXNrLktpbmRCCPpCBYIBAhABImcKBEtpbmQSFAoQS0lORF9VTlNQRUNJRklFRBAAEhkKFUtJTkRfU0VUVVBfQ09OVEFJTkVSUxABEhgKFEtJTkRfSU5TVEFMTF9TVFJPUFBZEAISFAoQS0lORF9SVU5fU1RST1BQWRADQjxaOmdpdGh1Yi5jb20vc3Ryb3BweS1pby9oYXRjaGV0LXdvcmtmbG93L2ludGVybmFsL3Byb3RvL2VkZ2ViBnByb3RvMw", [file_validate_validate]);

/**
 * @generated from message edge.Worker
 */
export type Worker = Message<"edge.Worker"> & {
  /**
   * @generated from field: string worker_name = 1;
   */
  workerName: string;

  /**
   * @generated from field: repeated edge.Task.Identifier acceptable_tasks = 2;
   */
  acceptableTasks: Task_Identifier[];

  /**
   * @generated from field: map<string, string> metadata = 6;
   */
  metadata: { [key: string]: string };
};

/**
 * @generated from message edge.Worker
 */
export type WorkerJson = {
  /**
   * @generated from field: string worker_name = 1;
   */
  workerName?: string;

  /**
   * @generated from field: repeated edge.Task.Identifier acceptable_tasks = 2;
   */
  acceptableTasks?: Task_IdentifierJson[];

  /**
   * @generated from field: map<string, string> metadata = 6;
   */
  metadata?: { [key: string]: string };
};

export type WorkerValid = Worker;

/**
 * Describes the message edge.Worker.
 * Use `create(WorkerSchema)` to create a new message.
 */
export const WorkerSchema: GenMessage<Worker, {jsonType: WorkerJson, validType: WorkerValid}> = /*@__PURE__*/
  messageDesc(file_edge_edge, 0);

/**
 * @generated from message edge.Task
 */
export type Task = Message<"edge.Task"> & {
};

/**
 * @generated from message edge.Task
 */
export type TaskJson = {
};

export type TaskValid = Task;

/**
 * Describes the message edge.Task.
 * Use `create(TaskSchema)` to create a new message.
 */
export const TaskSchema: GenMessage<Task, {jsonType: TaskJson, validType: TaskValid}> = /*@__PURE__*/
  messageDesc(file_edge_edge, 1);

/**
 * @generated from message edge.Task.Identifier
 */
export type Task_Identifier = Message<"edge.Task.Identifier"> & {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * @generated from field: string task_id = 2;
   */
  taskId: string;

  /**
   * @generated from field: edge.Task.Kind kind = 3;
   */
  kind: Task_Kind;
};

/**
 * @generated from message edge.Task.Identifier
 */
export type Task_IdentifierJson = {
  /**
   * @generated from field: string run_id = 1;
   */
  runId?: string;

  /**
   * @generated from field: string task_id = 2;
   */
  taskId?: string;

  /**
   * @generated from field: edge.Task.Kind kind = 3;
   */
  kind?: Task_KindJson;
};

export type Task_IdentifierValid = Task_Identifier;

/**
 * Describes the message edge.Task.Identifier.
 * Use `create(Task_IdentifierSchema)` to create a new message.
 */
export const Task_IdentifierSchema: GenMessage<Task_Identifier, {jsonType: Task_IdentifierJson, validType: Task_IdentifierValid}> = /*@__PURE__*/
  messageDesc(file_edge_edge, 1, 0);

/**
 * @generated from enum edge.Task.Kind
 */
export enum Task_Kind {
  /**
   * @generated from enum value: KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: KIND_SETUP_CONTAINERS = 1;
   */
  SETUP_CONTAINERS = 1,

  /**
   * @generated from enum value: KIND_INSTALL_STROPPY = 2;
   */
  INSTALL_STROPPY = 2,

  /**
   * @generated from enum value: KIND_RUN_STROPPY = 3;
   */
  RUN_STROPPY = 3,
}

/**
 * @generated from enum edge.Task.Kind
 */
export type Task_KindJson = "KIND_UNSPECIFIED" | "KIND_SETUP_CONTAINERS" | "KIND_INSTALL_STROPPY" | "KIND_RUN_STROPPY";

/**
 * Describes the enum edge.Task.Kind.
 */
export const Task_KindSchema: GenEnum<Task_Kind, Task_KindJson> = /*@__PURE__*/
  enumDesc(file_edge_edge, 1, 0);

