// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ratelproto/ratelproto.proto

package ratelproto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Table with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Table) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Table with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TableMultiError, or nil if none found.
func (m *Table) ValidateAll() error {
	return m.validate(true)
}

func (m *Table) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Generate

	for idx, item := range m.GetVirtualColumns() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TableValidationError{
						field:  fmt.Sprintf("VirtualColumns[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TableValidationError{
						field:  fmt.Sprintf("VirtualColumns[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TableValidationError{
					field:  fmt.Sprintf("VirtualColumns[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetIndexes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TableValidationError{
						field:  fmt.Sprintf("Indexes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TableValidationError{
						field:  fmt.Sprintf("Indexes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TableValidationError{
					field:  fmt.Sprintf("Indexes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetUnique() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TableValidationError{
						field:  fmt.Sprintf("Unique[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TableValidationError{
						field:  fmt.Sprintf("Unique[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TableValidationError{
					field:  fmt.Sprintf("Unique[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPrimaryKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TableValidationError{
					field:  "PrimaryKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TableValidationError{
					field:  "PrimaryKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPrimaryKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TableValidationError{
				field:  "PrimaryKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.TableName != nil {
		// no validation rules for TableName
	}

	if m.Schema != nil {
		// no validation rules for Schema
	}

	if len(errors) > 0 {
		return TableMultiError(errors)
	}

	return nil
}

// TableMultiError is an error wrapping multiple validation errors returned by
// Table.ValidateAll() if the designated constraints aren't met.
type TableMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TableMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TableMultiError) AllErrors() []error { return m }

// TableValidationError is the validation error returned by Table.Validate if
// the designated constraints aren't met.
type TableValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TableValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TableValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TableValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TableValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TableValidationError) ErrorName() string { return "TableValidationError" }

// Error satisfies the builtin error interface
func (e TableValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTable.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TableValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TableValidationError{}

// Validate checks the field values on UniqueConstraint with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UniqueConstraint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UniqueConstraint with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UniqueConstraintMultiError, or nil if none found.
func (m *UniqueConstraint) ValidateAll() error {
	return m.validate(true)
}

func (m *UniqueConstraint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return UniqueConstraintMultiError(errors)
	}

	return nil
}

// UniqueConstraintMultiError is an error wrapping multiple validation errors
// returned by UniqueConstraint.ValidateAll() if the designated constraints
// aren't met.
type UniqueConstraintMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UniqueConstraintMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UniqueConstraintMultiError) AllErrors() []error { return m }

// UniqueConstraintValidationError is the validation error returned by
// UniqueConstraint.Validate if the designated constraints aren't met.
type UniqueConstraintValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UniqueConstraintValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UniqueConstraintValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UniqueConstraintValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UniqueConstraintValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UniqueConstraintValidationError) ErrorName() string { return "UniqueConstraintValidationError" }

// Error satisfies the builtin error interface
func (e UniqueConstraintValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUniqueConstraint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UniqueConstraintValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UniqueConstraintValidationError{}

// Validate checks the field values on PrimaryKey with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PrimaryKey) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PrimaryKey with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PrimaryKeyMultiError, or
// nil if none found.
func (m *PrimaryKey) ValidateAll() error {
	return m.validate(true)
}

func (m *PrimaryKey) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PrimaryKeyMultiError(errors)
	}

	return nil
}

// PrimaryKeyMultiError is an error wrapping multiple validation errors
// returned by PrimaryKey.ValidateAll() if the designated constraints aren't met.
type PrimaryKeyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrimaryKeyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrimaryKeyMultiError) AllErrors() []error { return m }

// PrimaryKeyValidationError is the validation error returned by
// PrimaryKey.Validate if the designated constraints aren't met.
type PrimaryKeyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrimaryKeyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrimaryKeyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrimaryKeyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrimaryKeyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrimaryKeyValidationError) ErrorName() string { return "PrimaryKeyValidationError" }

// Error satisfies the builtin error interface
func (e PrimaryKeyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrimaryKey.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrimaryKeyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrimaryKeyValidationError{}

// Validate checks the field values on Index with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Index) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Index with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in IndexMultiError, or nil if none found.
func (m *Index) ValidateAll() error {
	return m.validate(true)
}

func (m *Index) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Unique

	// no validation rules for Where

	// no validation rules for Using

	// no validation rules for Concurrent

	if len(errors) > 0 {
		return IndexMultiError(errors)
	}

	return nil
}

// IndexMultiError is an error wrapping multiple validation errors returned by
// Index.ValidateAll() if the designated constraints aren't met.
type IndexMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndexMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndexMultiError) AllErrors() []error { return m }

// IndexValidationError is the validation error returned by Index.Validate if
// the designated constraints aren't met.
type IndexValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndexValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndexValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndexValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndexValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndexValidationError) ErrorName() string { return "IndexValidationError" }

// Error satisfies the builtin error interface
func (e IndexValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndex.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndexValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndexValidationError{}

// Validate checks the field values on Constraint with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Constraint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Constraint with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConstraintMultiError, or
// nil if none found.
func (m *Constraint) ValidateAll() error {
	return m.validate(true)
}

func (m *Constraint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Unique

	// no validation rules for PrimaryKey

	// no validation rules for DefaultValue

	// no validation rules for Raw

	// no validation rules for Check

	// no validation rules for ReferencesTable

	// no validation rules for ReferencesColumn

	// no validation rules for OnDelete

	// no validation rules for OnUpdate

	// no validation rules for ReferencesSchema

	if len(errors) > 0 {
		return ConstraintMultiError(errors)
	}

	return nil
}

// ConstraintMultiError is an error wrapping multiple validation errors
// returned by Constraint.ValidateAll() if the designated constraints aren't met.
type ConstraintMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConstraintMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConstraintMultiError) AllErrors() []error { return m }

// ConstraintValidationError is the validation error returned by
// Constraint.Validate if the designated constraints aren't met.
type ConstraintValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConstraintValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConstraintValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConstraintValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConstraintValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConstraintValidationError) ErrorName() string { return "ConstraintValidationError" }

// Error satisfies the builtin error interface
func (e ConstraintValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConstraint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConstraintValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConstraintValidationError{}

// Validate checks the field values on VirtualColumn with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VirtualColumn) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualColumn with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VirtualColumnMultiError, or
// nil if none found.
func (m *VirtualColumn) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualColumn) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SqlName

	// no validation rules for SqlType

	if all {
		switch v := interface{}(m.GetConstraints()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualColumnValidationError{
					field:  "Constraints",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualColumnValidationError{
					field:  "Constraints",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConstraints()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualColumnValidationError{
				field:  "Constraints",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IsNullable

	// no validation rules for IsArray

	if len(errors) > 0 {
		return VirtualColumnMultiError(errors)
	}

	return nil
}

// VirtualColumnMultiError is an error wrapping multiple validation errors
// returned by VirtualColumn.ValidateAll() if the designated constraints
// aren't met.
type VirtualColumnMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualColumnMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualColumnMultiError) AllErrors() []error { return m }

// VirtualColumnValidationError is the validation error returned by
// VirtualColumn.Validate if the designated constraints aren't met.
type VirtualColumnValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualColumnValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualColumnValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualColumnValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualColumnValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualColumnValidationError) ErrorName() string { return "VirtualColumnValidationError" }

// Error satisfies the builtin error interface
func (e VirtualColumnValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualColumn.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualColumnValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualColumnValidationError{}

// Validate checks the field values on Column with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Column) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Column with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ColumnMultiError, or nil if none found.
func (m *Column) ValidateAll() error {
	return m.validate(true)
}

func (m *Column) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Skip

	if all {
		switch v := interface{}(m.GetConstraints()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ColumnValidationError{
					field:  "Constraints",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ColumnValidationError{
					field:  "Constraints",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConstraints()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ColumnValidationError{
				field:  "Constraints",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ColumnMultiError(errors)
	}

	return nil
}

// ColumnMultiError is an error wrapping multiple validation errors returned by
// Column.ValidateAll() if the designated constraints aren't met.
type ColumnMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ColumnMultiError) AllErrors() []error { return m }

// ColumnValidationError is the validation error returned by Column.Validate if
// the designated constraints aren't met.
type ColumnValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ColumnValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ColumnValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ColumnValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ColumnValidationError) ErrorName() string { return "ColumnValidationError" }

// Error satisfies the builtin error interface
func (e ColumnValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sColumn.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ColumnValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnValidationError{}

// Validate checks the field values on OneToMany with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OneToMany) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OneToMany with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OneToManyMultiError, or nil
// if none found.
func (m *OneToMany) ValidateAll() error {
	return m.validate(true)
}

func (m *OneToMany) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RefName

	// no validation rules for Constraint

	// no validation rules for OnDeleteCascade

	// no validation rules for ExistedField

	if len(errors) > 0 {
		return OneToManyMultiError(errors)
	}

	return nil
}

// OneToManyMultiError is an error wrapping multiple validation errors returned
// by OneToMany.ValidateAll() if the designated constraints aren't met.
type OneToManyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OneToManyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OneToManyMultiError) AllErrors() []error { return m }

// OneToManyValidationError is the validation error returned by
// OneToMany.Validate if the designated constraints aren't met.
type OneToManyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OneToManyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OneToManyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OneToManyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OneToManyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OneToManyValidationError) ErrorName() string { return "OneToManyValidationError" }

// Error satisfies the builtin error interface
func (e OneToManyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOneToMany.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OneToManyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OneToManyValidationError{}

// Validate checks the field values on HasOne with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HasOne) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HasOne with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HasOneMultiError, or nil if none found.
func (m *HasOne) ValidateAll() error {
	return m.validate(true)
}

func (m *HasOne) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RefName

	// no validation rules for Constraint

	// no validation rules for OnDeleteCascade

	// no validation rules for OnDeleteSetNull

	// no validation rules for ExistedField

	if len(errors) > 0 {
		return HasOneMultiError(errors)
	}

	return nil
}

// HasOneMultiError is an error wrapping multiple validation errors returned by
// HasOne.ValidateAll() if the designated constraints aren't met.
type HasOneMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HasOneMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HasOneMultiError) AllErrors() []error { return m }

// HasOneValidationError is the validation error returned by HasOne.Validate if
// the designated constraints aren't met.
type HasOneValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HasOneValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HasOneValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HasOneValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HasOneValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HasOneValidationError) ErrorName() string { return "HasOneValidationError" }

// Error satisfies the builtin error interface
func (e HasOneValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHasOne.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HasOneValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HasOneValidationError{}

// Validate checks the field values on BelongsTo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BelongsTo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BelongsTo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BelongsToMultiError, or nil
// if none found.
func (m *BelongsTo) ValidateAll() error {
	return m.validate(true)
}

func (m *BelongsTo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ForeignKey

	// no validation rules for OwnerKey

	if len(errors) > 0 {
		return BelongsToMultiError(errors)
	}

	return nil
}

// BelongsToMultiError is an error wrapping multiple validation errors returned
// by BelongsTo.ValidateAll() if the designated constraints aren't met.
type BelongsToMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BelongsToMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BelongsToMultiError) AllErrors() []error { return m }

// BelongsToValidationError is the validation error returned by
// BelongsTo.Validate if the designated constraints aren't met.
type BelongsToValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BelongsToValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BelongsToValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BelongsToValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BelongsToValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BelongsToValidationError) ErrorName() string { return "BelongsToValidationError" }

// Error satisfies the builtin error interface
func (e BelongsToValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBelongsTo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BelongsToValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BelongsToValidationError{}

// Validate checks the field values on ManyToMany with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ManyToMany) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ManyToMany with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ManyToManyMultiError, or
// nil if none found.
func (m *ManyToMany) ValidateAll() error {
	return m.validate(true)
}

func (m *ManyToMany) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RefOnDeleteCascade

	// no validation rules for RefConstraint

	// no validation rules for BackRefOnDeleteCascade

	// no validation rules for BackRefConstraint

	if m.PivotTable != nil {

		if all {
			switch v := interface{}(m.GetPivotTable()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ManyToManyValidationError{
						field:  "PivotTable",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ManyToManyValidationError{
						field:  "PivotTable",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPivotTable()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ManyToManyValidationError{
					field:  "PivotTable",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ManyToManyMultiError(errors)
	}

	return nil
}

// ManyToManyMultiError is an error wrapping multiple validation errors
// returned by ManyToMany.ValidateAll() if the designated constraints aren't met.
type ManyToManyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ManyToManyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ManyToManyMultiError) AllErrors() []error { return m }

// ManyToManyValidationError is the validation error returned by
// ManyToMany.Validate if the designated constraints aren't met.
type ManyToManyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ManyToManyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ManyToManyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ManyToManyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ManyToManyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ManyToManyValidationError) ErrorName() string { return "ManyToManyValidationError" }

// Error satisfies the builtin error interface
func (e ManyToManyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sManyToMany.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ManyToManyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ManyToManyValidationError{}

// Validate checks the field values on Relation with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Relation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Relation with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RelationMultiError, or nil
// if none found.
func (m *Relation) ValidateAll() error {
	return m.validate(true)
}

func (m *Relation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Relation.(type) {
	case *Relation_OneToMany:
		if v == nil {
			err := RelationValidationError{
				field:  "Relation",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetOneToMany()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "OneToMany",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "OneToMany",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetOneToMany()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RelationValidationError{
					field:  "OneToMany",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Relation_ManyToMany:
		if v == nil {
			err := RelationValidationError{
				field:  "Relation",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetManyToMany()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "ManyToMany",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "ManyToMany",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetManyToMany()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RelationValidationError{
					field:  "ManyToMany",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Relation_HasOne:
		if v == nil {
			err := RelationValidationError{
				field:  "Relation",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetHasOne()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "HasOne",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "HasOne",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetHasOne()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RelationValidationError{
					field:  "HasOne",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Relation_BelongsTo:
		if v == nil {
			err := RelationValidationError{
				field:  "Relation",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBelongsTo()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "BelongsTo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RelationValidationError{
						field:  "BelongsTo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBelongsTo()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RelationValidationError{
					field:  "BelongsTo",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return RelationMultiError(errors)
	}

	return nil
}

// RelationMultiError is an error wrapping multiple validation errors returned
// by Relation.ValidateAll() if the designated constraints aren't met.
type RelationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RelationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RelationMultiError) AllErrors() []error { return m }

// RelationValidationError is the validation error returned by
// Relation.Validate if the designated constraints aren't met.
type RelationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RelationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RelationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RelationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RelationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RelationValidationError) ErrorName() string { return "RelationValidationError" }

// Error satisfies the builtin error interface
func (e RelationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRelation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RelationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RelationValidationError{}
